#!/usr/bin/env python3
"""Populate the `modelContext` field on admin1 records: the larger model's
general knowledge about each unit's culture, religiosity, rule of law,
urbanism and tourism exposure — the factors a rater should weigh *in addition
to* the research dossier.

Why this exists: dossiers document incidents where visibility and reporting
exist (cities); units with no dossier signal read as "safe" to a rater even
though under-documentation is not safety. This field gives the rater the
context to resist that asymmetry, and it corrects the blind spot of dossiers
being incident-density-driven.

Notes are descriptive, never scores. Default note applies to units with no
specific knowledge. Idempotent: rerunning refreshes all notes.

Usage:
    python3 tools/admin1_knowledge.py            # apply to data/admin1.json
    python3 tools/admin1_knowledge.py --dry-run
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

DEFAULT_NOTE = ("No distinctive sub-national knowledge from the model. Treat this unit "
                "as inheriting the national climate exactly — including its social "
                "conservatism, informal norms and unreported violence. Under-"
                "documentation here is not safety, and it is not danger either.")

# iso3 -> list of (lowercase substring, note). First match wins.
KNOWLEDGE: dict[str, list[tuple[str, str]]] = {
    "MEX": [
        ("distrito federal", "Mexico City: North America's most established LGBT scene after US/Canadian metros; Pride draws hundreds of thousands; city human-rights institutions functional; full anonymity in Roma/Zona Rosa."),
        ("jalisco", "Guadalajara: large visible scene and Pride; but Jalisco cartel violence is extreme and police are distrusted; state socially conservative Catholic belt."),
        ("nuevo leon", "Monterrey: wealthy industrial north; state-level 'morality' legal actions documented; conservative business-Catholic culture; cartel presence."),
        ("quintana roo", "Cancún/Riviera Maya: massive international tourism economy creates a real protective envelope; most cosmopolitan corner of Mexico outside CDMX."),
        ("yucatan", "Mérida: repeatedly ranked Mexico's safest city; conservative Catholic society but strong rule of law and indigenous Maya cultural tolerance of gender variance historically."),
        ("baja california sur", "Los Cabos tourism economy; international envelope similar to Cancún."),
        ("baja california", "Tijuana border dynamics; cartel violence; but border cities historically more socially permeable."),
        ("chihuahua", "Ciudad Juárez cartel-violence legacy; conservative north; weak rule of law in sierra regions."),
        ("coahuila", "Northern industrial state; conservative; cartel corridors."),
        ("sinaloa", "Culiacán: cartel heartland — rule of law effectively shared with the Sinaloa cartel; socially conservative; narco-culture machismo."),
        ("tamaulipas", "Gulf-cartel heartland among Mexico's most lawless; arbitrary violence risk dominates any LGBT-specific factor."),
        ("guerrero", "Among Mexico's most violent; Acapulco tourism enclave coexists with near-total impunity in the interior."),
        ("michoacan", "Cartel (CJNG/Familia legacy) contested; conservative Catholic heartland (Morelia/Uruguay valley tradition)."),
        ("veracruz", "High violent-crime rates; conservative Gulf-coast society; weak institutions."),
        ("oaxaca", "Indigenous-majority, traditional communal governance (usos y costumbres) is socially conservative; muxe third-gender tradition in Juchitán is a documented local tolerance pocket."),
        ("chiapas", "Poorest state; indigenous traditionalism strongly conservative; Zapatista zones have their own governance."),
        ("puebla", "Deep Catholic conservative heartland; large university city (Puebla/Buap) with a small scene."),
        ("guanajuato", "Catholic Bajío conservatism (León/Irapuato); PAN stronghold; but growing industrial cosmopolitanism."),
        ("queretaro", "Wealthy Bajío; conservative but orderly, low violence."),
        ("aguascalientes", "Small wealthy Bajío state; conservative; high institutional quality."),
        ("san luis potosi", "Bajío-north transition; conservative; moderate violence."),
        ("zacatecas", "CJNG/Sinaloa corridor; violence spike; conservative."),
        ("durango", "Cartel corridor; conservative norteño culture."),
        ("sonora", "Border/agro-industrial north; conservative; cartel corridors in the sierra."),
        ("colima", "Small Pacific state; per-capita violence among the highest; Manzanillo port cartel contest."),
        ("nayarit", "Cartel corridor; conservative."),
        ("morelos", "Cuernavaca weekend-tourism proximity to CDMX; violence rates high; socially mixed."),
        ("hidalgo", "Conservative central highlands; Pachuca modest urbanism."),
        ("tlaxcala", "Smallest state; conservative; CDMX orbit."),
        ("mexico", "State of México: vast CDMX conurbation periphery — anonymity near the capital, but Ecatepec/Neza violence and machismo culture documented."),
        ("campeche", "Quiet Gulf south; conservative but low violence."),
        ("tabasco", "Poor Gulf south; conservative; weak institutions."),
    ],
    "CAN": [
        ("ontario", "Toronto: Canada's largest scene, strong provincial human-rights enforcement; institutions robust province-wide."),
        ("quebec", "Montréal: historic gay village, Quebec's distinct civil-law culture is among North America's most secular and permissive; strong institutions."),
        ("british columbia", "Vancouver: Davie Village scene; BC is consistently Canada's most progressive province on LGBT issues (human-rights code first to include sexual orientation in 1992); strong institutions."),
        ("alberta", "Calgary/Edmonton scenes exist but Alberta is the conservative-prairie exception: strongest religious-right political current in Canada, though Canadian law still binds — climate difference, not legal difference."),
        ("saskatchewan", "Rural prairie conservatism; small scenes in Saskatoon/Regina; institutions function."),
        ("manitoba", "Winnipeg modest scene; prairie conservatism; institutions function."),
        ("nova scotia", "Halifax: small but historically significant scene (first Pride east of Ontario); Atlantic provinces socially traditional but institutions protective."),
        ("new brunswick", "Bilingual Atlantic province; socially traditional; small Moncton/Fredericton scene."),
        ("newfoundland", "Most socially traditional province (strong church culture); St. John's has a small warm scene; geographic isolation."),
        ("prince edward", "Smallest province; traditional but close-knit and low-crime; institutions protective."),
        ("northwest territories", "Small population; Yellowknife modest openness; northern indigenous communities traditional."),
        ("nunavut", "Inuit governance; tiny population; traditional social norms; no scene; but community-scale, low arbitrary violence."),
        ("yukon", "Whitehorse small-town openness typical of Canadian north; institutions protective."),
    ],
    "GBR": [
        ("england", "London/Brighton/Manchester: world-class scene and institutions; outside metros, market-town England is socially mixed — generally safe but visibility varies; strong rule of law everywhere."),
        ("scotland", "Edinburgh/Glasgow scenes; Scottish law and politics consistently more progressive on LGBT rights than Westminster; strong institutions."),
        ("wales", "Cardiff scene; Welsh society socially conservative in the valleys/rural west but institutions strongly protective; low violence."),
        ("northern ireland", "Distinct legal history (decriminalisation only 1982, marriage equality only 2020 by Westminster imposition); strongest religious-conservative political current in the UK; Belfast scene exists but is discreet; sectarian-policing legacy affects trust."),
    ],
    "AUS": [
        ("new south wales", "Sydney: Oxford Street scene, Mardi Gras — the Southern Hemisphere's largest; NSW police historically hostile (1970s-90s), now institutionally reformed with documented hate-crime prosecution."),
        ("victoria", "Melbourne: strong scene; Victoria consistently Australia's most progressive state on LGBT law and policing; coronial/oversight institutions active."),
        ("queensland", "Brisbane/Cairns scenes; Queensland historically the conservative state (decriminalisation only 1991, Joh Bjelke-Petersen police legacy) — attitudes have modernised but rural QLD remains traditional."),
        ("western australia", "Perth scene; geographic isolation; WA decriminalised 1990; socially conservative mining-state culture but institutions protective."),
        ("south australia", "Adelaide: first Australian state to decriminalise (1975); small-city conservatism coexists with functioning institutions."),
        ("tasmania", "Historically the most hostile (last state to decriminalise, 1997; Galloway case); now legally among the most progressive after rapid reversal — but small, close-knit society where visibility carries social cost in rural towns."),
        ("northern territory", "Darwin: tiny scene; NT has Australia's harshest general social climate and highest violence rates; indigenous community norms traditional; institutions thin."),
        ("australian capital territory", "Canberra: Australia's most progressive jurisdiction on paper (self-government since 1989 built on public-service culture); small scene."),
        ("other territories", "External territories; tiny populations; effectively Australian-law governed."),
    ],
    "BRA": [
        ("sao paulo", "São Paulo city: the world's largest Pride parade and Latin America's deepest scene; state institutions (Defensoria, MP) actively prosecute LGBT-phobia; but state police (PM) violence is documented in peripheries."),
        ("rio de jeneiro", "Rio: visible beach-culture scene (Ipanema/Copacabana); state police violence extreme but not LGBT-targeted specifically; favela governance (milícia/trafico) imposes local moral codes in places."),
        ("minas gerais", "Belo Horizonte: large established scene; Minas is Brazil's swing-state heartland — socially traditional interior, urban institutions strong."),
        ("rio grande do sul", "Porto Alegre: strong scene; southernmost state, European-immigration culture, historically Brazil's most progressive region (first domestic-partnership recognitions)."),
        ("parana", "Curitiba: solid scene; southern state, more socially conservative than RS (evangelical belt in interior) but institutions strong."),
        ("santa catarina", "Florianópolis/Balneário Camboriú: tourism-heavy coast with visible summer scene; SC is Brazil's safest state by homicide rate and institutions are the country's strongest — any violence-data signal here reflects reporting density, not comparative danger."),
        ("bahia", "Salvador: Brazil's Afro-Brazilian cultural capital with deep gender-nonconformist traditions (transformismo culture); but Bahia's interior is socially conservative and state violence rates high."),
        ("pernambuco", "Recife: established scene and strong university activism; interior (sertão) traditional."),
        ("ceara", "Fortaleza: large beach-tourism scene; drag culture visible; interior conservative."),
        ("paraiba", "João Pessoa modest scene; small traditional northeastern state; documented violence rates high but not LGBT-specific in pattern."),
        ("rio granda do norte", "Natal: tourism coast with visible scene; interior traditional."),
        ("distrito federal", "Brasília: institutions, diplomacy, organized scene; planned city with anonymity limits but strong institutional presence."),
        ("goias", "Goiânia: agribusiness heartland, socially conservative (evangelical belt); scene small but exists."),
        ("mato grosso", "Cuiabá: agribusiness frontier conservatism; institutions thin."),
        ("mato grosso do sul", "Campo Grande: agribusiness frontier; traditional."),
        ("espirito santo", "Vitória modest scene; state socially traditional but violence rates moderate."),
        ("amazonas", "Manaus: isolated metro with a scene; interior under minimal state presence."),
        ("para", "Belém: established scene; interior Amazon under weak governance."),
        ("maranhao", "São Luís: traditional; among Brazil's poorest institutions."),
        ("piaui", "Teresina: traditional northeast interior."),
        ("alagoas", "Maceió: tourism coast; Alagoas historically among the highest violence rates; conservative interior."),
        ("sergipe", "Small traditional northeastern state; Aracaju modest scene."),
        ("acre", "Western Amazon frontier; traditional; institutions thin."),
        ("rondonia", "Amazon frontier state; socially conservative migration culture."),
        ("roraima", "Northernmost frontier; institutions thin."),
        ("amapa", "Northern frontier; institutions thin."),
        ("tocantins", "Newest state; frontier conservatism."),
    ],
    "IND": [
        ("delhi", "National capital: India's most organized scene, NGOs (Naz legacy, Humsafar Trust), Pride since 2008; police harassment documented but courts and media provide real recourse; vast anonymity."),
        ("mahārāshtra", "Mumbai: India's scene capital — Bollywood-adjacent visibility, Khotwadi/hijra communities, strongest NGO infrastructure; Maharashtra police extortion documented historically but institutional recourse real."),
        ("tamil nādu", "Chennai: thirunangai/aravani activism is India's most institutionalized trans organizing (Transgender Welfare Board first in India, 2008); temples-and-tradition culture has historic gender-variant roles; society conservative but state machinery protective."),
        ("karnātaka", "Bengaluru: tech-city cosmopolitanism, large closeted scene, active NGOs; police generally restrained."),
        ("west bengal", "Kolkata: historic hijra visibility and first Indian trans-activism (1970s); Left-era institutions; but West Bengal political violence and police partisanship documented."),
        ("kerala", "India's highest social-development indicators; Kochi Queerala/Trans Pride organized; society matrilineal-legacy but publicly moralistic; institutions strong."),
        ("gujarāt", "Ahmedabad/Surat business cosmopolitanism with strong socially-conservative Hindu-nationalist governance; state machinery efficient but majoritarian."),
        ("rājasthān", "Jaipur modest scene; traditional princely-state conservatism; tourist envelope in cities."),
        ("uttar pradesh", "India's most populous, poorest-governed heartland; Lucknow/Kanpur historic hijra culture (nirvan community) coexists with severe police arbitrariness; rule of law weakest among major states."),
        ("bihār", "Poorest governance in India; Patna small scene; caste violence and police arbitrariness documented; hijra communities exist but under extreme precarity."),
        ("madhya pradesh", "Central heartland; Bhopal/Indore modest scenes; traditional."),
        ("punjab", "Strong Sikh-traditional society; Chandigarh (shared capital) has an organized scene; emigration culture means families police gender hard, but violence is social, not state-driven."),
        ("haryāna", "Most khap-panchayat (caste-council) influence in India; documented honour-violence tradition; close to Delhi but socially far."),
        ("chandīgarh", "Planned shared capital city: North India's most cosmopolitan pocket; organized scene."),
        ("himāchal pradesh", "Hill state; relatively gentle traditionalism; Shimla/Kullu tourism."),
        ("uttarākhand", "Hill state; conservative but low-violence."),
        ("jammu and кашmīr", ""),
        ("jammu and kashmīr", "Militarized, communications-restricted; conservative Muslim society; LGBT existence socially invisible; state attention on security only."),
        ("ladākh", "Buddhist-majority, tourism-exposed; socially traditional but non-policing."),
        ("assam", "Guwahati: Northeast India's organized scene hub; Assamese society historically tolerant of gender variance (hijra-friendly festival traditions); institutions improving."),
        ("manipur", "Insurgency-legacy, AFSPA policing; but Manipuri society has documented trans visibility (nupi-manbi community) with relative social space."),
        ("meghālaya", "Matrilineal Khasi society — Northeast's most gender-flexible traditional culture; Shillong cosmopolitan; Christianity socially conservative but community-based, not state-enforced."),
        ("nāgāland", "Baptist-conservative society; Hornbill-festival tourism; gender norms strictly policed socially."),
        ("mizoram", "Tight-knit Christian society; socially conservative."),
        ("tripura", "Small northeastern state; documented violence rates high (general crime + instability); institutions thin — danger is general-lawlessness, not LGBT-targeted."),
        ("arunāchal pradesh", "", ),
        ("arunāchal", "Indigenous societies, generally non-policing on gender but socially traditional; restricted-access border state."),
        ("sikkim", "India's most socially liberal small state by survey data; tourism culture; organized modest scene."),
        ("odisha", "Bhubaneswar modest scene; Odia temple culture has historic gender-variant roles (hijra at festivals); rural society traditional."),
        ("chhattīsgarh", "Naxalite-insurgency zones in the south; weak governance; Raipur small scene."),
        ("jhārkhand", "Mining-frontier state; weak institutions; Ranchi modest scene."),
        ("andhra pradesh", "Hyderabad legacy scene now in Telangana; coastal AP traditional with hijra community presence."),
        ("telangāna", "Hyderabad: major organized scene, historic Mehaboob-ki-Mehendi hijra culture, strong NGO base; police relatively restrained."),
        ("goa", "Tourism economy creates India's most permissive coastal envelope; international exposure; small resident scene; police tolerant in tourist zones."),
        ("puducherry", "French-colonial legacy, Auroville international community; socially permissive pocket."),
        ("andaman", "Islands; tiny population; tourism; effectively mainland norms."),
        ("dādra", "Small union territories; negligible scene; mainland norms."),
        ("lakshadweep", "Tiny Muslim-majority islands; strictly conservative; essentially no visitor LGBT exposure."),
    ],
    "DEU": [
        ("berlin", "Europe's most open LGBT metropolis: Schöneberg legacy, vast trans infrastructure, city-government explicitly protective; anonymity total."),
        ("hamburg", "St. Pauli scene; wealthy cosmopolitan port; strong institutions."),
        ("nordrhein-westfalen", "Cologne: Germany's largest Pride and deepest scene; Ruhr cities diverse; NRW institutions strong."),
        ("bayern", "Munich scene is large and accepted, but Bavaria is CSU-Catholic-conservative in the countryside; institutions fully protective — climate difference only."),
        ("baden-württemberg", "Stuttgart scene; southwest prosperous, mildly conservative rural areas; institutions strong."),
        ("hessen", "Frankfurt: major scene, banking cosmopolitanism."),
        ("niedersachsen", "Hanover/Braunschweig modest scenes; rural Lower Saxony traditional; institutions strong."),
        ("rheinland-pfalz", "Mainz modest; rural wine-country traditional."),
        ("schleswig-holstein", "Kiel modest scene; north socially calm; institutions strong."),
        ("bremen", "Small city-state with a scene; institutions strong."),
        ("saarland", "Small traditional border state; Saarbrücken modest scene."),
        ("brandenburg", "Rural east: AfD-strongest belt, documented anti-LGBT incidents in small towns; Potsdam (Berlin orbit) is the exception."),
        ("sachsen", "Dresden/Leipzig have real scenes (Leipzig notably alternative-friendly), but rural Saxony is AfD-core territory with the highest documented anti-LGBT incident density in Germany; police protection functions but social hostility is organized."),
        ("sachsen-anhalt", "Rural east; AfD strong; Magdeburg modest scene; small towns hostile."),
        ("thüringen", "Rural east; AfD-strong (Höcke-wing); Erfurt modest scene; small-town hostility documented."),
        ("mecklenburg-vorpommern", "Most rural, most depopulated east; AfD strong; Baltic tourism coast somewhat cosmopolitan."),
    ],
    "ESP": [
        ("comunidad de madrid", "Madrid (Chueca): Europe's most visible LGBT capital alongside Berlin — municipal/regional institutions supportive even under conservative regional government; Pride is the continent's largest; total anonymity."),
        ("cataluña", "", ),
        ("catalu", "Barcelona: world-class scene, city-level protections, vast tourism envelope; Catalan institutions explicitly protective."),
        ("país vasco", "", ),
        ("país", "Bilbao/San Sebastián: Basque institutions among Spain's most progressive on LGBT rights; strong autonomy, strong policing."),
        ("comunitat valenciana", "Valencia/Benidorm: large scene plus Europe's biggest LGBT tourism enclave (Sitges-adjacent culture); regional law explicitly protective."),
        ("illes balears", "Mallorca/Ibiza: international tourism envelope among Europe's most permissive."),
        ("canarias", "Canary Islands: year-round LGBT tourism economy (Maspalomas Pride); island society traditional off-resort but envelope real."),
        ("comunidad foral de navarra", "Pamplona modest scene; Navarre politically conservative but institutions protective under national law."),
        ("andaluc", "Seville/Málaga/Torremolinos: Costa del Sol tourism envelope; Andalusian society traditional-Catholic in the interior but gender-expression tolerance in culture (transformismo, feria culture) and institutions protective."),
        ("galicia", "A Coruña/Vigo modest scenes; rural Galician society traditional, matriarchal in places; institutions protective."),
        ("arag", "Zaragoza modest scene; traditional interior."),
        ("cantabria", "Santander conservative summer-coast society; institutions protective."),
        ("principado de asturias", "Gijón/Oviedo modest; mining-region traditionalism; institutions protective."),
        ("castilla y le", "", ),
        ("castilla y león", "Most traditional interior of Spain (Valladolid/Salamanca university cities the exception); rural conservatism real but national law binds fully."),
        ("castilla-la mancha", "Traditional rural interior; Toledo/Albacete modest; institutions protective."),
        ("extremadura", "Poorest, most rural region; traditional; institutions protective."),
        ("regi", "Murcia: among the most conservative regions politically (church influence strong); institutions still bound by national law."),
        ("la rioja", "Small traditional wine region."),
        ("ciudad autónoma de ceuta", "Spanish North-African enclave: Muslim-majority population under Spanish law — legal protection exists but social exposure severe; border-securitized."),
        ("ciudad autónoma de melilla", "Spanish North-African enclave: same profile as Ceuta."),
    ],
    "COL": [
        ("bogota", "Bogotá (Chapinero): Latin America's second-deepest scene after São Paulo; District government explicitly protective (LGBTI citizen centers); Constitutional Court jurisprudence continent-leading; high-altitude anonymity of an 8-million city."),
        ("antioquia", "Medellín: Colombia's second scene, barrio-manila visibility, strong trans activism history; Paisa culture is traditionally machista AND entrepreneurial-cosmopolitan; documented violence is general homicide economy, not LGBT-specific targeting — Medellín is today among Colombia's safer large cities."),
        ("valle del cauca", "Cali: third scene, strong Afro-Colombian trans visibility (especially Buenaventura-legacy communities); city violence high but general."),
        ("atlántico", "", ),
        ("atlántico", "Barranquilla: Carnival culture has documented gender-transgressive traditions (marimondas, transformismo); city violence is cartel-general."),
        ("bol", "Cartagena: tourism economy with resort envelope; historic Afro-Colombian transformismo culture; city violence moderate."),
        ("santander", "Bucaramanga: conservative Andean city but institutional order among Colombia's better."),
        ("caldas", "Manizales coffee-axis: university city, conservative Catholic culture, low violence."),
        ("risaralda", "Pereira coffee-axis: modest scene, moderate violence."),
        ("quind", "Armenia coffee-axis: tourism, small-city conservatism, low violence."),
        ("nari", "Pasto conservative highland; border violence (Nariño corridor) is general-conflict, not LGBT-specific."),
        ("norte de santander", "Cúcuta border city: weakest institutional environment in Colombia; violence general."),
        ("choc", "Quibdó: among Colombia's weakest state presence; armed-group governance; danger is general."),
        ("caquet", "FARC-dissident corridors; general lawlessness dominates."),
        ("arauca", "Border conflict zone; general lawlessness."),
        ("meta", "Villavicencio llanos gateway; mixed governance."),
        ("guaviare", "Coca frontier; minimal state."),
        ("putumayo", "Coca frontier; minimal state."),
        ("amazonas", "Leticia: tourism, small population, general frontier dynamics."),
        ("vichada", "Eastern llanos frontier: minimal state presence; general lawlessness."),
        ("vaup", "Amazonian indigenous region: communal traditional governance; almost no visitor traffic."),
        ("guain", "Eastern Amazon frontier: minimal state presence."),
        ("cauca", "Popayán: conservative Andean city; rural north Cauca is a dissident-conflict corridor — danger is general; Nasa/Misak indigenous communal governance traditional."),
        ("la guajira", "Wayuu indigenous governance in much of the peninsula; conservative but community-based."),
        ("magdalena", "Santa Marta tourism coast; modest institutions."),
        ("córdoba", "", ),
        ("córdoba", "Montería: traditional Caribbean interior; paramilitary legacy."),
        ("sucre", "Traditional Caribbean interior; paramilitary legacy."),
        ("cesar", "Valledupar: traditional; coal-economy violence legacy."),
        ("tolima", "Ibagué: traditional Andean; post-conflict calm."),
        ("huila", "Neiva: traditional Andean south."),
        ("boyac", "Tunja: Colombia's most traditional Catholic highland culture; low violence; conservative but orderly."),
        ("cundinamarca", "Bogotá's surrounding department: commuter belt, mixed."),
        ("casanare", "Llanos oil frontier; conservative."),
        ("archipi", "San Andrés: Caribbean island tourism economy; raizal culture; resort envelope."),
    ],
    "ARG": [
        ("ciudad autónoma de buenos aires", "", ),
        ("ciudad aut", "CABA (City of Buenos Aires): Latin America's most institutionalized LGBT-friendly jurisdiction — city anti-discrimination law since 1996, gender-identity pioneer rulings, vast visible scene in Palermo/Constitución, tourism economy; the hemisphere's most open urban environment south of Mexico City."),
        ("buenos aires", "Buenos Aires Province (conurbano): working-class periphery — visibility carries more risk than in CABA; police (Bonaerense) historically brutal and corrupt; La Plata and Mar del Plata (tourism, established scene) are the province's safer urban pockets."),
        ("córdoba", "", ),
        ("córdoba", "Córdoba city: Argentina's second scene with deep university activism, but Córdoba province is the country's clerical-conservative heartland (Catholic university culture, strong church political influence); city/countryside split is sharp."),
        ("santa fe", "Rosario: major city with a scene, but Argentina's narcoviolence epicenter — danger is general, not LGBT-specific."),
        ("mendoza", "Mendoza: wine-tourism cosmopolitanism; Andean society moderately traditional; institutions solid."),
        ("tucum", "Tucumán: Argentina's most socially conservative province (church political power strongest here, 2000s-era anti-vice ordinances); San Miguel scene small and discreet."),
        ("salta", "Northwest traditional-Catholic stronghold; conservative politics; Salta city discreet scene."),
        ("jujuy", "Northwest traditional; indigenous-communitarian conservatism; 2023 protest-crackdown documented police harshness."),
        ("neuqu", "Patagonian oil province; socially calm, institutions moderate."),
        ("río negro", "", ),
        ("río negro", "Patagonia; Bariloche tourism; socially liberal-leaning Patagonian culture."),
        ("chubut", "Patagonia; small cities, socially calm."),
        ("santa cruz", "Kirchner-home Patagonian province; tiny population, socially calm."),
        ("tierra del fuego", "Ushuaia: tourism end-of-the-world economy; famously Argentina's first province to authorize same-sex unions (2000s governor decision); tiny close-knit population."),
        ("la pampa", "Quiet agricultural province; low social salience."),
        ("entre r", "Litoral province; traditional but calm."),
        ("corrientes", "Northeast traditional-Catholic; conservative."),
        ("misiones", "Northeast; Jesuit-mission heritage conservative; tourism (Iguazú) envelope."),
        ("chaco", "Poor northeast; institutions thin."),
        ("formosa", "Feudal-politics province (Insfrán machine); institutions weak; society traditional."),
        ("santiago del estero", "Among Argentina's most traditional and politically feudal provinces; institutions weak."),
        ("catamarca", "Northwest conservative; tiny scene."),
        ("la roja", "La Rioja: small conservative northwest province; family-politics culture."),
        ("san juan", "Andean conservative; mining economy."),
        ("san luis", "Small conservative province; orderly."),
    ],
    "ITA": [
        ("nord-ovest", "Milan/Turin/Genoa: Italy's wealthiest, most cosmopolitan northwest — Milan has the country's deepest scene and most efficient institutions; Ligurian coast tourism; regional politics mixed but northern society is the most European-facing."),
        ("nord-est", "Venice/Verona/Bologna-adjacent northeast: wealthy, Catholic-league traditionalism in Veneto (documented regional-council hostility), but strong municipal institutions; Trento/Bolzano autonomous provinces are Alpine-central-European in culture."),
        ("centro", "Rome/Florence/Bologna: the institutional heart — Rome's scene is large if more discreet than Milan, Bologna historically Italy's most LGBT-friendly city (Arcigay birthplace, leftist municipal tradition), Tuscany tourism envelope; central regions combine visibility with the strongest civil-society infrastructure."),
        ("sud", "Naples/Bari/Palermo-adjacent mainland south: Campania and Puglia carry Italy's highest documented anti-LGBT violence rates AND strong femminiello/traditional gender-variant cultures in Naples — the south is simultaneously the most dangerous and the most culturally gender-fluid part of Italy; institutional protection weakest, family honor culture strongest."),
        ("isole", "Sicily and Sardinia: Catania beating (2025) documented Sicilian risk; Sicily has historic femminiello-adjacent traditions; Sardinia is insular-traditional with low immigration and strong family codes; both islands have small organized scenes in Palermo/Cagliari and tourism envelopes in Taormina (historic gay-tourism destination since the 19th century) and Costa Smeralda."),
    ],
    "POL": [
        ("masovian", "Warsaw: Poland's largest scene, Parada Równości draws tens of thousands; capital's liberal bubble coexists with national conservative governance; institutions functional under EU-law constraints."),
        ("greater poland", "Poznań: strong scene, March of Equality established; Wielkopolska relatively pragmatic-conservative."),
        ("lower silesian", "Wrocław: most cosmopolitan western city after Warsaw; active scene; German-legacy openness."),
        ("pomeranian", "Gdańsk/Tricity: most progressive big-city government in Poland (Pawel Adamowicz legacy, civic tolerance programs); Equality Marches function."),
        ("west pomeranian", "Szczecin: western border city; modest scene; calmer politically."),
        ("lubusz", "Smallest western voivodeship; border-region pragmatism; low salience."),
        ("silesian", "Katowice: industrial Upper Silesia — socially conservative Catholic worker culture but dense urbanism provides anonymity; scene modest and organized."),
        ("lesser poland", "Kraków: major scene and Equality Marches, university cosmopolitanism; but surrounding Małopolska countryside is among Poland's most traditional-Catholic (gminy anti-LGBT resolution heartland)."),
        ("łódź voivodeship", "", ),
        ("dz voivodeship", "Łódź: post-industrial city with modest scene; voivodeship mixed."),
        ("kuyavian-pomeranian", "Bydgoszcz/Toruń modest scenes; mixed urban-rural."),
        ("warmian-masurian", "Olsztyn: rural northeast; conservative."),
        ("podlaskie", "Białystok 2019 Equality March mob violence is Poland's most infamous incident — the northeast is the country's most nationalistically conservative region; institutions protective on paper, socially hostile in practice."),
        ("lublin", "Lublin: east Poland's most conservative major region (church influence strongest); Equality Marches held under police protection against counter-demonstrations."),
        ("subcarpathian", "Rzeszów/Podkarpacie: Poland's most religiously conservative voivodeship — highest church attendance, most gminy anti-LGBT resolutions, border-traditional culture; scene exists only in Rzeszów, discreetly."),
        ("świętokrzyskie voivodeship", "", ),
        ("tokrzyskie", "Kielce: rural south-central; among the most conservative; low salience."),
        ("opole", "Opole: German-minority region — minority status correlates with slightly more liberal attitudes; modest."),
    ],
    "NGA": [
        ("lagos", "Lagos: Nigeria's largest and only real scene — underground clubs, organized NGOs (The Initiative for Equal Rights), vast-city anonymity; but Lagos is SSMAA-arrest jurisdiction with documented police raids and extortion; the scene persists because scale overwhelms enforcement."),
        ("abuja federal", "Abuja: diplomatic capital — embassy-protected NGO space, but 2018 mass-arrest precedent; federal district police are the most politically directed."),
        ("rivers", "Port Harcourt: oil-city underground scene, documented police raids; Niger Delta militancy adds general lawlessness."),
        ("kano", "Northern Nigeria's most religiously governed major city: hisbah (morality police) institutionalized, sharia criminal law applied, documented mob violence against gender-nonconforming people; among the most dangerous places in Africa for a discovered trans visitor."),
        ("kaduna", "Sharia-criminal-law state with mixed Christian/Muslim south; hisbah-style enforcement documented; 2023 arrest wave of trans-presenting people."),
        ("sokoto", "Sharia heartland; conservative governance total; no visible scene."),
        ("zamfara", "First state to adopt sharia criminal law (1999); banditry epidemic means general lawlessness compounds."),
        ("kebbi", "Sharia state; conservative."),
        ("katsina", "Sharia state; banditry-affected."),
        ("jigawa", "Sharia state; rural."),
        ("bauchi", "Sharia state; documented anti-LGBT prosecution attempts (2007 mass-trial precedent); general insecurity."),
        ("yobe", "Sharia state; Boko Haram-affected — security forces and insurgents both hostile."),
        ("borno", "Sharia state; insurgency epicenter — the least protective environment in Nigeria."),
        ("gombe", "Sharia state; moderate."),
        ("adamawa", "Sharia-criminal provisions apply; Christian-minority south of the state somewhat different in practice."),
        ("taraba", "Sharia provisions; ethnically fragmented."),
        ("niger", "Niger State: sharia criminal provisions; vast rural; banditry-affected."),
        ("kogi", "North-central transition state; mixed."),
        ("kwara", "Ilorin: emirate-influenced but south-adjacent; moderate conservatism."),
        ("nasarawa", "North-central; mixed."),
        ("plateau", "Jos: ethno-religious flashpoint city; Christian south of the state more moderate but violence is communal."),
        ("benue", "Christian-majority middle belt; traditional but no sharia; communal violence documented."),
        ("oyo", "Ibadan: southwest Yoruba culture — historically the most gender-expression-tolerant Nigerian culture (transvestite priesthood traditions, less homophobic than north or southeast); no sharia; scene discreet."),
        ("ogun", "Yoruba southwest; Abeokuta; moderate."),
        ("osun", "Yoruba southwest; Osogbo arts culture relatively open by Nigerian standards."),
        ("ondo", "Yoruba southwest; moderate."),
        ("ekiti", "Yoruba southwest; small state; moderate."),
        ("edo", "Benin City: Edo culture with historic gender-fluid ritual roles; but documented police extortion and 2017-era arrests; southern, no sharia."),
        ("delta", "Oil south-south; Warri violence general; no sharia."),
        ("anambra", "Southeast Igbo heartland: no sharia but Igbo society is strongly conservative on gender and SSMAA convictions have come from here (2022 Emekachi 12 case — 67 years); vigilantism documented."),
        ("imo", "Southeast; conservative; documented mob incidents."),
        ("abia", "Southeast; conservative."),
        ("enugu", "Southeast's largest city; conservative but urban; IPOB-separatist tension adds general instability."),
        ("ebonyi", "Southeast rural; conservative."),
        ("cross river", "Calabar: southern coastal, relatively mixed culture; tourism (Obudu) small."),
        ("akwa ibom", "Uyo: southern oil state; conservative Christian but orderly."),
        ("bayelsa", "Niger Delta creek state; general lawlessness."),
    ],
    "IDN": [
        ("jakarta special", "Jakarta: Indonesia's largest scene — organized NGOs (Ardhanary Institute, GWL-INA), underground club culture, 20-million anonymity; national police raids and FPI-style vigilante groups (now banned) documented; the scene persists at scale but public events require police negotiation."),
        ("bali", "Bali: Hindu-majority island where national Islamic-conservative pressure applies weakest; international tourism creates a real envelope; Seminyak scene visible; Indonesian police generally restrained on-island due to tourism economics."),
        ("special region of yogyakarta", "Yogyakarta: sultanate-university city — Indonesia's most documented waria community organization (Pesantren Waria al-Fatah, the world's only waria pesantren, operates here); student-city tolerance coexists with conservative currents."),
        ("aceh", "Aceh: Indonesia's only province with formal sharia criminal law (qanun jinayat) — caning for same-sex intimacy documented (2017 caning of two men), wilayatul hisbah morality police patrol public behavior; the most dangerous province in Indonesia for a discovered trans visitor."),
        ("west java", "Bandung/Bogor/Depok: the most populous province surrounds Jakarta with the strongest Islamist-organizational presence (Garut, Depok ordinances documented); vigilante pressure historically highest here; but Bandung's university scene exists."),
        ("east java", "Surabaya: Indonesia's second metro with an organized scene; East Java pesantren culture is conservative and documented anti-LGBT mobilization occurred here; Madura-adjacent traditionalism."),
        ("central java", "Semarang/Solo: Solo (Surakarta) is the most Islamist-organization-dense city in Indonesia (documented FPI-legacy pressure); Yogyakarta-adjacent regions mixed."),
        ("north sumatra", "Medan: large city with discreet scene; North Sumatra mixed Batak-Muslim-Christian; conservative currents strong but pluralist."),
        ("west sumatra", "Padang: Minangkabau matrilineal society is strongly Islamic-conservative in public morality despite matriliny; documented raids; Pariaman anti-LGBT bylaw precedent."),
        ("south sulawesi", "Makassar: 2023 documented raid wave and anti-LGBT mobilization; but Bugis culture historically recognizes five genders (calabai/bissu traditions) — the deepest traditional gender-variant culture in Indonesia coexists with modern Islamist hostility."),
        ("south sumatra", "Palembang: large city, discreet scene; moderately conservative."),
        ("banten", "Jakarta's western industrial flank; Tangerang documented anti-LGBT ordinance attempts; conservative."),
        ("west nusa tenggara", "Lombok/Mataram: more conservative Muslim society than Bali next door; Sumbawa traditional."),
        ("east nusa tenggara", "Kupang/Flores: Christian-majority province — different conservative current (Catholic/Protestant), less vigilante-Islamist; Maumere documented incidents are church-driven."),
        ("papua", "Papua: militarized conflict province; Indonesian security-force presence dominates; Papuan society traditionally gender-conservative; LGBT issues subsumed under security politics."),
        ("west papua", "West Papua: same profile as Papua — securitized, minimal civil society space."),
        ("riau", "Pekanbaru: Malay-Muslim conservative; oil economy."),
        ("riau islands", "Batam: Singapore-adjacent free-trade islands — most cosmopolitan non-Jakarta/Bali environment; ferry-distance tolerance."),
        ("lampung", "Southern Sumatra gateway; rural conservative."),
        ("jambi", "Central Sumatra; Malay conservative; rural."),
        ("bengkulu", "Small conservative Sumatran province."),
        ("bangka", "Tin-mining islands; Malay-conservative; small."),
        ("kalimantan", "", ),
        ("kalimantan", "Borneo provinces: migrant-majority frontier society, less Islamization pressure than Sumatra/Java; Banjarmasin/Pontianak/Samarinda modest scenes; Dayak traditional culture non-Islamic in interior."),
        ("gorontalo", "Small province with the strongest per-capita Islamist-ordinance record in eastern Indonesia (2015 anti-LGBT bylaw attempts)."),
        ("sulawesi", "Sulawesi provinces: Bugis/Makassar/Minahasan cultures — Minahasa (North Sulawesi) is Christian-majority and markedly more relaxed; Central/Southeast Sulawesi Muslim-conservative."),
        ("maluku", "Ambon: post-sectarian-conflict society; Christian-Muslim balance; conservative both ways; small scene."),
    ],
    "MYS": [
        ("kuala lumpur", "KL: Malaysia's entire visible scene — underground clubs, organized NGOs (PT Foundation, Justice for Sisters litigate from here), federal-territory status means no state-religious-bureau raids of the rural kind; anonymity of 2 million."),
        ("selangor", "Malaysia's most urbanized, wealthiest state wrapping KL; diverse; state Islamic authority active but urban density dilutes enforcement."),
        ("penang", "George Town: historic cosmopolitan port, Chinese-majority plurality, tourism; most liberal social climate in peninsular Malaysia alongside KL; state government opposition-legacy independent streak."),
        ("johor", "Johor Bahru: Singapore's commuter twin — Singapore exposure makes JB the most cosmopolitan Malay-majority city; sultanate historically independent-minded; scene discreet but real."),
        ("perak", "Ipoh: mixed society; state moderately conservative."),
        ("negeri sembilan", "Adat perpatih matrilineal tradition — Negeri Sembilan's Malay customary law is matrilineal, historically the most gender-flexible Malay culture; modern Islamic authorities conservative nonetheless."),
        ("malacca", "Melaka: tourism heritage city, Chinese-Peranakan plurality; socially among the more relaxed Malay-majority states."),
        ("kelantan", "Kelantan: PAS (Islamist party) governance since 1990 — state sharia enforcement most active in Malaysia, documented canings under state enactments, public-entertainment morality codes; the most dangerous state for a discovered trans visitor."),
        ("terengganu", "Terengganu: PAS-governed — state sharia enforcement active (2000 attempted caning precedent under hudud proposals), conservative coast."),
        ("kedah", "Kedah: PAS-influenced conservative Malay heartland (Mahathir's home state); rural traditional."),
        ("perlis", "Smallest, most rural state; conservative."),
        ("pahang", "Large conservative sultanate state; Genting tourism enclave apart, socially traditional."),
        ("sabah", "Sabah (East Malaysia, Borneo): Christian-plurality Kadazan-Dusun society — markedly less religiously policed than the peninsula; Kota Kinabalu cosmopolitan-tourism; no state sharia-bureau culture of the peninsula kind; the most socially relaxed Malaysian environment."),
        ("sarawak", "Sarawak (East Malaysia, Borneo): Iban/Chinese plurality, secular-regionalist politics, Kuching relaxed by Malaysian standards; least religiously policed alongside Sabah."),
        ("putrajaya", "Federal administrative capital; bureaucrat city; no scene, no salience."),
        ("labuan", "Federal offshore-finance island; tiny population; mixed."),
    ],
    "TUR": [
        ("stanbul", "İstanbul: Turkey's entire LGBT infrastructure — Beyoğlu/Kadıköy trans community is historic and visible, Lambdaistanbul since 1993, hormone access via private clinics; Pride banned since 2015 and dispersed with arrests, but between events daily life in central districts is the most open in the Muslim-majority world; 16-million anonymity."),
        ("zmir", "İzmir: Turkey's most secular city by every measure — Alevi/secular-migration culture, opposition-governed municipality, Alsancak scene visible, historically tolerated street presence; the safest social climate in Turkey."),
        ("ankara", "Ankara: capital's diplomatic and university scene — Kaos GL (Turkey's oldest LGBT NGO, founded 1994) operates here; LGBT events were city-wide banned 2017-2019 (lifted by courts); bureaucracy city, discreet but organized."),
        ("eski", "Eskişehir: Turkey's classic university city — two major universities, most youthful and anonymous interior city, student liberalism documented; safest interior climate."),
        ("antalya", "Antalya: Russia/Europe mass-tourism coast — tourism economy creates a real envelope in resort zones; city itself conservative-nationalist."),
        ("muğla", "Muğla province (Bodrum/Marmaris/Fethiye): Turkey's most international tourism coast — Bodrum's beach-club culture is the most permissive public space in the country; resort envelope genuine."),
        ("ayd", "Aydın (Kuşadası/Didim): Aegean tourism coast, secular-Alevi migration communities; relatively relaxed."),
        ("çanakkale", "Çanakkale: Aegean-Marmara; Gallipoli nationalism coexists with secular coastal towns; university presence."),
        ("edirne", "Edirne/Thrace: European-facing border region, secular Trakya culture (alcohol-tolerant Roma-influenced coast towns), historically most European social climate."),
        ("kırklareli", "Thrace coast: secular, European-facing, low salience."),
        ("tekirdağ", "Thrace/Marmara coast: İstanbul overflow, secular."),
        ("muğla province", ""),
        ("konya", "Konya: Turkey's most religiously conservative major province — Mevlana-tourism apart, Islamist-organizational heartland (Anadolu youth movements), documented vigilante pressure; Konya crowds have attacked LGBT-presenting people."),
        ("şanlıurfa", "Şanlıurfa: prophet-city — Turkey's most religious province by practice metrics; tribal-conservative social structure; LGBT existence socially invisible and extremely dangerous if discovered."),
        ("erzurum", "Erzurum: eastern Anatolia's most conservative city — nationalist-Islamist synthesis strongest here."),
        ("kayseri", "Kayseri: conservative industrial Anatolian-tiger city; religious business class; discreet."),
        ("trabzon", "Trabzon: Black Sea nationalism — documented far-right mobilization (2000s-era attacks on missionaries/dissenters); conservative."),
        ("rize", "Rize: Erdoğan's home province; deepest conservative-Islamist loyalty in Turkey."),
        ("diyarbak", "Diyarbakır: Kurdish movement's capital — HDP/Yeşil Sol politics formally embrace LGBT rights in party platform (unique in the region), but Kurdish society itself is strongly traditional; documented tension between movement-level tolerance and street-level conservatism; Hebun LGBT association operates here."),
        ("mardin", "Mardin: Arab/Kurdish/Syriac traditional society; conservative."),
        ("van", "Van: Kurdish east; conservative; post-2016 trusteed-municipality politics."),
        ("hakk", "Hakkâri: most remote, most securitized Kurdish border province — conflict governance dominates everything; traditional society."),
        ("şırnak", "Şırnak: war-destroyed/rebuilt border province; securitized; traditional."),
        ("batman", "Batman: oil-Kurdish conservative city."),
        ("siirt", "Siirt: Kurdish-Arab conservative southeast province; low salience but high danger if discovered."),
        ("tunceli", "Dersim/Tunceli: Alevi-majority — Turkey's most religiously heterodox and socially liberal province by voting and survey data; tiny population."),
        ("gaziantep", "Gaziantep: southeastern industrial metropolis — conservative but commercially cosmopolitan, large Syrian-refugee population changes street dynamics."),
        ("adana", "Adana: southern metro — historically more relaxed port-city culture than the Anatolian interior, working-class tolerance documented."),
        ("mersin", "Mersin: Mediterranean port — most secular southern city, Alevi and migrant communities, relative openness."),
        ("hatay", "Hatay: historically Turkey's most pluralist province (Alawite/Christian/Sunni/Jewish mosaic, Antioch Greek legacy) — post-2023 earthquake devastated but social culture was the country's most mixed."),
        ("sivas", "Sivas: site of the 1993 Madımak Alevi-burning — symbol of Sunni-conservative militancy; conservative."),
        ("yozgat", "Yozgat: MHP-nationalist conservative heartland shorthand in Turkish political culture."),
        ("çorum", "Çorum: 1980 sectarian-pogrom legacy; conservative."),
        ("malatya", "Malatya: 2007 Zirve missionary murders legacy; conservative nationalist."),
        ("elaz", "Elazığ: nationalist-conservative east."),
        ("afyonkarahisar", "Afyon: conservative interior crossroads."),
        ("kütahya", "Kütahya: conservative interior."),
        ("nevşehir", "Nevşehir/Cappadocia: tourism economy creates balloon-town international exposure; provincial society conservative."),
        ("bursa", "Bursa: fourth city — industrial, conservative-nationalist politics but urban anonymity real; modest discreet scene."),
        ("kocaeli", "Kocaeli: İstanbul industrial spillover; mixed."),
        ("sakarya", "Sakarya: conservative Marmara; Adapazarı."),
        ("bolu", "Bolu: documented xenophobic-mayor politics (Özcan-era refugee hostility signals broader minoritarian hostility); conservative."),
        ("samsun", "Samsun: Black Sea metropolis; nationalist-conservative."),
        ("ord u", ""),
        ("ordu", "Ordu: Black Sea conservative coast."),
        ("giresun", "Giresun: Black Sea; nationalist-conservative."),
        ("artvin", "Artvin: eastern Black Sea — Hopa is a secular-left pocket (Laz culture), province mixed."),
        ("ardahan", "Ardahan: remote northeastern border; low salience."),
        ("kars", "Kars: northeastern border; mixed Alevi/Kurdish/Caucasus cultures; low salience."),
        ("iğdır", "Iğdır: Azerbaijani-majority border province; secular-Alevi elements; low salience."),
        ("ağrı", "Ağrı: conservative Kurdish border province."),
        ("muş", "Muş: conservative Kurdish province."),
        ("bitlis", "Bitlis: conservative Kurdish province."),
        ("bingöl", "Bingöl: most conservative province by religiosity surveys."),
        ("adıyaman", "Adıyaman: Arab/Kurdish conservative; Kahta traditional."),
        ("kahramanmaraş", "Kahramanmaraş: 1978 pogrom legacy; among the most conservative provinces."),
        ("kilis", "Kilis: small border province; conservative."),
        ("osmaniye", "Osmaniye: nationalist-conservative south."),
        ("isparta", "Isparta: nationalist-conservative lake district."),
        ("burdur", "Burdur: conservative lake district."),
        ("denizli", "Denizli: Pamukkale tourism apart, Anatolian-tiger conservative industry."),
        ("uşak", "Uşak: conservative interior Aegean."),
        ("manisa", "Manisa: Aegean hinterland; conservative-nationalist."),
        ("balıkesir", "Balıkesir: Aegean-Marmara mixed coast; Edremit-gulf retirement cosmopolitanism vs nationalist interior."),
        ("yalova", "Yalova: small Marmara province; mixed."),
        ("bilecik", "Bilecik: small conservative interior."),
        ("düzce", "Düzce: mixed Black Sea-Caucasus migrant culture; conservative."),
        ("zonguldak", "Zonguldak: coal-coast; working-class, mixed."),
        ("bartın", "Bartın: small Black Sea; conservative."),
        ("karabük", "Karabük: steel town; conservative."),
        ("kastamonu", "Kastamonu: Black Sea interior; conservative."),
        ("sinop", "Sinop: quiet Black Sea; low salience."),
        ("amasya", "Amasya: conservative interior."),
        ("tokat", "Tokat: conservative interior."),
        ("gümüşhane", "Gümüşhane: conservative northeast."),
        ("bayburt", "Bayburt: Turkey's most nationalist-voting province consistently; conservative."),
        ("erzincan", "Erzincan: mixed Alevi/Sunni; moderate."),
        ("aksaray", "Aksaray: conservative central."),
        ("karaman", "Karaman: conservative central (Karaman abuse-scandal town 2016 reflects institutional opacity)."),
        ("niğde", "Niğde: conservative central."),
        ("kırşehir", "Kırşehir: Alevi-heritage central province (Ahilik tradition); moderate."),
        ("kırıkkale", "Kırıkkale: military-industrial conservative."),
        ("çankırı", "Çankırı: most conservative near-capital province."),
    ],
    "RUS": [
        ("moscow oblast", "Moscow Oblast wraps the capital; commuter belt shares Moscow's relative anonymity without its scene."),
        ("moscow", "Moscow: Russia's entire visible-underground scene — clubs operate discreetly, hormone access via private medicine, Pride banned since 2006 and attempts crushed, but the 12-million capital offers the only real anonymity; post-2023 'extremist movement' designation makes any organizing criminal everywhere including here."),
        ("saint petersburg", "Saint Petersburg: Russia's most European city — historic tolerance reputation, the scene operates most openly here (though post-2023 raids hit Petersburg venues first), cultural capital anonymity."),
        ("kaliningrad", "Kaliningrad: EU-surrounded exclave — Polish/Lithuanian TV and cross-border traffic historically created Russia's most European-exposed social climate; scene small."),
        ("chechnya", "Chechnya: purge-scale persecution since 2017 — abductions, secret prisons, torture killings, family-honor killings encouraged by authorities; being LGBT is treated as a capital offense in practice; the most dangerous jurisdiction in Europe/Central Asia for a trans person."),
        ("dagestan", "Dagestan: Caucasus purge spillover — documented vigilante killings, police collusion with families, honor violence; Islamic-conservative governance strongest in Russia here."),
        ("ingushetia", "Ingushetia: same Caucasus pattern as Chechnya/Dagestan — clan-honor governance, effectively zero tolerance."),
        ("kabardino-balkaria", "Kabardino-Balkaria: North Caucasus religious-conservative enforcement climate; less purge-scale than Chechnya but street-level danger high."),
        ("karachay-cherkessia", "Karachay-Cherkessia: North Caucasus conservative; low salience but dangerous if visible."),
        ("north ossetia", "North Ossetia: Caucasus conservative-Christian counterpart; traditional honor culture; Beslan-legacy securitization."),
        ("adygea", "Adygea: small Caucasus republic; traditional; low salience."),
        ("stavropol krai", "Stavropol: Caucasus gateway — Cossack patrol culture documented (moral-policing auxiliaries), conservative."),
        ("krasnodar krai", "Krasnodar/Sochi: resort coast paradox — Sochi's Olympic-legacy international infrastructure vs Cossack-patrol conservatism; scene underground."),
        ("rostov oblast", "Rostov: southern gateway; Cossack culture; conservative; war-adjacent since 2022 (refugee/military corridor)."),
        ("volgograd oblast", "Volgograd: conservative south; low salience."),
        ("astrakhan oblast", "Astrakhan: Caspian multiethnic (Tatar/Kazakh) conservative."),
        ("saratov oblast", "Saratov: Volga provincial conservatism."),
        ("samara oblast", "Samara: Volga industrial city — largest non-capital scene remnant; provincial conservatism outside Togliatti."),
        ("tatarstan", "Tatarstan: Kazan is Russia's third-most-cosmopolitan city (student, IT, Islamic-modernist Tatar culture historically less homophobic than Russian Orthodoxy); but republican authorities enforce federal line strictly post-2023."),
        ("bashkortostan", "Bashkortostan: Ufa industrial-conservative; 2024 protest crackdown documented heavy-handed policing; Muslim-majority traditional."),
        ("sverdlovsk oblast", "Yekaterinburg: Russia's 'third capital' — strongest regional civil-society infrastructure (Ural human-rights tradition), scene exists underground; industrial conservatism in the oblast."),
        ("novosibirsk oblast", "Novosibirsk: Siberia's science-capital (Akademgorodok legacy) — historically Russia's most liberal big city outside the capitals; underground scene; conservative turn post-2022."),
        ("chelyabinsk oblast", "Chelyabinsk: industrial Urals conservatism (the 'meteor city' macho culture); low salience."),
        ("kemerovo oblast", "Kemerovo: Kuzbass mining region — among Russia's most conservative working-class provinces."),
        ("perm krai", "Perm: Urals cultural city; provincial conservatism."),
        ("krasnoyarsk krai", "Krasnoyarsk: Siberian industrial; conservative."),
        ("irkutsk oblast", "Irkutsk: Baikal tourism city; Siberian frontier culture relatively rough-and-tolerant of personal eccentricity; low salience."),
        ("tyumen oblast", "Tyumen: oil-region prosperity conservatism."),
        ("khanty-mansiysk", "Khanty-Mansiysk/Yugra: oil towns — migrant work culture, money conservatism; low salience."),
        ("yamalo-nenets", "Yamalo-Nenets: gas-frontier north; rotational-worker society; low salience."),
        ("sakha republic", "Sakha/Yakutia: largest region — Yakut society traditionally conservative on gender; extreme isolation; shamanic heritage distinct from Orthodoxy but not permissive."),
        ("buryatia", "Buryatia: Buddhist-majority republic — Buddhist institutional conservatism documented (2010s anti-gay statements); war-heavy casualty region since 2022."),
        ("tuva", "Tuva: most socially conservative republic by survey data; documented anti-LGBT statements from government; clan society."),
        ("kalmykia", "Kalmykia: Buddhist republic; institutional conservatism; low salience."),
        ("murmansk oblast", "Murmansk: Arctic north — the 2023 'international LGBT movement' extremism trial (first of its kind) happened here; closed militarized society."),
        ("arkhangelsk oblast", "Arkhangelsk: Pomor north; conservative; Solovki-legacy."),
        ("komi republic", "Komi: northern prison-colony region (Russia's largest penal infrastructure); harsh institutional environment."),
        ("karelia", "Karelia: Finnish-border republic — Nordic-adjacent history but post-2022 border securitization reversed any liberalization; conservative."),
        ("leningrad oblast", "Leningrad Oblast wraps Saint Petersburg without sharing its culture; provincial."),
        ("pskov oblast", "Pskov: border province; conservative; proximity to Baltics historically softened slightly."),
        ("smolensk oblast", "Smolensk: Belarus-border; conservative."),
        ("kaluga oblast", "Kaluga: Moscow orbit industrial; low salience."),
        ("tula oblast", "Tula: Moscow orbit arms-industry; conservative."),
        ("tver oblast", "Tver: Moscow-Petersburg corridor; provincial conservatism."),
        ("yaroslavl oblast", "Yaroslavl: Golden Ring conservatism; documented regional anti-LGBT initiatives (2010s propaganda-law testing ground)."),
        ("vladimir oblast", "Vladimir: Golden Ring conservative."),
        ("ivanovo oblast", "Ivanovo: depressed textile province; conservative."),
        ("kostroma oblast", "Kostroma: provincial conservative."),
        ("ryazan oblast", "Ryazan: the 2006 propaganda-law first case (Fetisov) happened here — pioneer of the legal architecture now federal; conservative."),
        ("lipetsk oblast", "Lipetsk: industrial conservative."),
        ("voronezh oblast", "Voronezh: black-earth capital; nationalist-conservative documented."),
        ("tambov oblast", "Tambov: agricultural conservative."),
        ("belgorod oblast", "Belgorod: war-border province — shelling, militarization, evacuation regimes; conservatism compounded by war governance."),
        ("kursk oblast", "Kursk: war-border — 2024 Ukrainian incursion zone; martial governance."),
        ("bryansk oblast", "Bryansk: war-border province; militarized."),
        ("oryol oblast", "Oryol: provincial conservative."),
        ("penza oblast", "Penza: provincial conservative (Sennaya network-case legacy of FSB arbitrariness)."),
        ("ulyanovsk oblast", "Ulyanovsk: Volga provincial; cadet-school culture conservatism."),
        ("orenburg oblast", "Orenburg: Kazakh-border steppe; mixed conservative; Cossack presence."),
        ("kurgan oblast", "Kurgan: poorest Urals province; depressed conservatism."),
        ("omsk oblast", "Omsk: Siberian industrial; conservative."),
        ("tomsk oblast", "Tomsk: Siberian university city (Russia's Athens) — student culture historically most liberal Siberian pocket; conservative turn post-2022."),
        ("khabarovsk krai", "Khabarovsk: Far East metropolis; 2020 protest-crackdown legacy; frontier conservatism."),
        ("primorsky krai", "Vladivostok: Pacific port — Asian-facing, historically roughest-tolerant port culture; naval securitization."),
        ("sakhalin oblast", "Sakhalin: island oil-frontier; rotational society."),
        ("kamchatka krai", "Kamchatka: volcanic frontier; tiny population; low salience."),
        ("magadan oblast", "Magadan: Gulag-legacy far northeast; harsh closed society."),
        ("chukotka", "Chukotka: Arctic frontier; Abramovich-legacy paternalism; tiny population."),
        ("amur oblast", "Amur: China-border; conservative frontier."),
        ("zabaykalsky krai", "Zabaykalye: Mongolia-border depressed frontier; conservative."),
        ("jewish autonomous oblast", "Jewish AO: nominally Jewish-autonomous, actually Russia's poorest province; ironic name, bleak reality; low salience."),
        ("altai krai", "Altai Krai: agricultural south Siberia; conservative."),
        ("altai republic", "Altai Republic: spiritual-tourism region (neo-shamanic, Rerikh-pilgrim culture) — eccentricity-tolerant in a frontier way; tiny population."),
        ("khakassia", "Khakassia: small Siberian republic; conservative."),
        ("mari el", "Mari El: Finno-Ugric republic; pagan-heritage conservatism; low salience."),
        ("mordovia", "Mordovia: prison-colony heartland (many of Russia's harshest IK colonies are here — the penal destination risk matters nationally, not locally); conservative."),
        ("chuvashia", "Chuvashia: Volga republic; conservative."),
        ("udmurtia", "Udmurtia: arms-industry republic (Izhevsk); conservative."),
        ("kirov oblast", "Kirov/Vyatka: depressed northeast; conservative."),
        ("vologda oblast", "Vologda: Russian-north conservatism; prison-colony presence."),
        ("novgorod oblast", "Novgorod: provincial northwest; low salience."),
        ("nenets autonomous", "Nenets: Arctic oil frontier; tiny population."),
    ],
    "ZAF": [
        ("gauteng", "Johannesburg/Pretoria: South Africa's economic heart — deepest scene infrastructure, organized NGOs (Iranti, GALA legacy), Constitutional Court jurisprudence world-leading; township violence coexists with Sandton/Soweto extremes; police service dysfunctional but courts function."),
        ("western cape", "Cape Town: Africa's most open LGBT city — De Waterkant scene, Pride, tourism economy, and the Western Cape is the only province with consistently better-functioning provincial services; conservative religious communities in the Cape Flats/Boland coexist with the continent's most permissive urban envelope."),
        ("kwazulu-natal", "Durban: substantial scene and historic Indian-Ocean cosmopolitanism, but KZN carries South Africa's highest documented anti-LGBT violence rates (corrective-rape cases cluster here), strongest traditional-Zulu authority influence (inkhundla/chiefs), and July-2021 unrest showed how fast order collapses; urban protection vs township danger is the sharpest split in the country."),
        ("eastern cape", "Most rural and traditional Xhosa heartland (initiation-school culture strongly gender-normative); documented violence high; institutions weakest; Nelson Mandela Bay modest scene."),
        ("free state", "Boer-heartland conservatism — Bloemfontein modest scene; farm-community traditionalism; Afrikaner Calvinist influence strongest here."),
        ("north west", "Rustenburg mining belt — migrant-labor hostels, traditional Tswana authority, weak institutions; low salience but low protection."),
        ("mpumalanga", "Lowveld tourism (Kruger-adjacent) envelope in reserves vs traditional rural society outside; institutions thin."),
        ("limpopo", "Most rural province; traditional Venda/Pedi authority strong; documented anti-LGBT sentiment high in rural surveys; institutions thinnest."),
        ("nothern cape", "Largest, emptiest province; Karoo conservatism; low salience, low protection; Kimberley modest."),
    ],
    "FRA": [
        ("île-de-france", "Paris/Île-de-France: France's scene capital — Le Marais, national organizations (Inter-LGBT, OUTrans, Acceptess-T) all headquartered here, Pride draws hundreds of thousands; total anonymity; institutions fully protective."),
        ("auvergne-rhône-alpes", "Lyon: France's second scene, established since the 1970s (first French LGBT center founded in Lyon region); Grenoble/Annecy progressive-alpine; rural Auvergne traditional."),
        ("provence-alpes-côte d'azur", "Marseille/Nice/Cannes: Mediterranean tourism envelope — Riviera resorts historically permissive (Cassis/Cap d'Agde adjacent culture); Marseille working-class cosmopolitanism; FN/RN political strength in the hinterland is the counter-current."),
        ("occitanie", "Montpellier: France's most LGBT-dense city per capita (university, municipal equality programs since 2000s); Toulouse similar; rural Languedoc/Roussillon traditional; Mediterranean coast permissive-tourism."),
        ("nouvelle-aquitaine", "Bordeaux: established scene, bourgeois-liberal city culture; Basque coast (Biarritz/Hendaye) tourism-permissive; rural Limousin/Périgord traditional-low-salience."),
        ("grand est", "Strasbourg: European-institutions cosmopolitanism; Alsace historically conservative-Catholic but Strasbourg's European bubble overrides; Lorraine industrial decline conservatism."),
        ("hauts-de-france", "Lille: large student scene; Nord industrial-socialist municipal tradition protective; Picardie rural RN-voting conservatism."),
        ("normandie", "Rouen/Caen modest scenes; coastal tourism; rural Pays de Caux traditional."),
        ("pays de la loire", "Nantes: France's most consistently left-liberal big city (municipal LGBT programs strong); Angers modest; Vendée rural is France's most Catholic-conservative department (Chouannerie legacy)."),
        ("bretagne", "Rennes: strong student-scene and progressive Breton identity politics; rural Brittany Catholic-conservative legacy but low salience today."),
        ("centre-val de loire", "Tours/Orléans modest scenes; Loire-valley rural traditionalism; low salience."),
        ("bourgogne-franche-comté", "Dijon/Besançon modest university scenes; rural Burgundy traditional; Besançon historically progressive-municipal."),
        ("corse", "Corsica: strongest regional-nationalist and clan-conservative culture in France — documented anti-LGBT vandalism incidents (2010s Ajaccio Pride attacks); island society close-knit with high social control; no meaningful scene; French law nominally applies but local enforcement culture is hostile."),
    ],
    "PHL": [
        ("ncr", "Metro Manila: the Philippines' scene capital — Malate/Poblacion visible gay bars, trans NGOs (STRAP, T-WANG) operate nationally from here, media visibility highest (Filipino entertainment's bakla/beauty-pageant culture gives public presence no ASEAN neighbor matches); city ordinances in Quezon City/Makati explicitly protect gender expression."),
        ("calabarzon", "Southern Tagalog: Manila's commuter orbit — urban spill-over tolerance; provincial towns traditional-Catholic."),
        ("central luzon", "Pampanga/Bulacan: Angeles City's entertainment-bar economy creates documented trans visibility (and exploitation risk); Bulacan is church-conservative; mixed province-by-province."),
        ("central visayas", "Cebu: the Visayas' metro — Cebuano society is famously more relaxed on gender presentation than Manila (beauty-pageant/bakla culture deeply integrated); tourism economy; ordinances modest."),
        ("western visayas", "Iloilo/Bacolod: gentler Visayan culture, strong university presence; Boracay (Aklan) tourism envelope with visible trans workforce in hospitality."),
        ("davao region", "Davao City: Duterte-family governance — law-and-order authoritarianism protects bodies but the mayor's office has been openly hostile to LGBT visibility (Duterte's on-record rape-joke of a missionary, anti-SOGIE stance); city ordinance exists but enforcement culture is patriarchal; scene discreet."),
        ("northern mindanao", "Cagayan de Oro: Mindanao's most LGBT-organized city (documented Pride events, city anti-discrimination ordinance passed); Christian-Mindanao urbanism."),
        ("soccsksargen", "South-central Mindanao: most conservative Christian-settler region — General Santos traditional; adjacent Muslim-Mindanao culture; SOGIE-bill resistance strongest here; documented local hostility incidents."),
        ("armm", "Bangsamoro (Muslim Mindanao): sharia-influenced governance framework for Muslim residents under the BARMM organic law — gender expression socially invisible; for a visitor, Islamic-conservative social codes dominate; Cotabato City is the administrative center."),
        ("zamboanga peninsula", "Zamboanga: Christian-Muslim border city — Latin-Asian culture, moderately conservative; security operations periodic."),
        ("caraga", "Northeast Mindanao frontier; Butuan/ Surigao traditional; mining-frontier culture."),
        ("bicol region", "Bicol: the most devoutly Catholic region (Peñafrancia devotion) — socially conservative; Naga/Legazpi modest scenes; but bakla visibility culturally tolerated in pageant culture."),
        ("eastern visayas", "Tacloban: post-Yolanda rebuilt; traditional; low salience."),
        ("ilocos region", "Ilocos: Marcos-heartland conservatism — traditional Ilocano society, strong church influence; Vigan tourism small-scale."),
        ("cagayan valley", "Northern valley; traditional agricultural conservatism; Tuguegarao modest."),
        ("car", "Cordillera highlands: indigenous Igorot societies — gender norms traditional but mountain-community smallness means low harassment salience; Baguio is the region's university city with a modest scene and cooler climate of tolerance."),
        ("mimaropa", "Palawan tourism economy — El Nido/Coron international envelope; Puerto Princesa modest; islands otherwise traditional."),
    ],
    "PER": [
        ("lima", "Lima: Peru's entire scene — Barranco/Miraflores visible nightlife, MHOL and more organizations, trans activism institutionalized since the 2000s; 10-million anonymity; Lima police extortion of street-based trans women documented (the danger is concentrated in specific districts and for specific populations — visitors in Miraflores/Barranco experience a Latin-American-normal urban climate)."),
        ("municipalidad metropolitana de lima", "Metropolitan Lima municipality: same profile as Lima province — the scene, the NGOs, the anonymity; district-level variation (Miraflores/San Isidro protective, Callao-adjacent cone districts harsher)."),
        ("el callao", "Callao port: working-class port culture, higher general crime; adjacent to Lima's protective bubble but rougher."),
        ("cusco", "Cusco: Machu Picchu tourism economy — international visitor presence makes Cusco the most foreigner-normalized Andean city; modest visible scene; tourism police function."),
        ("arequipa", "Arequipa: Peru's second city — strong regional identity, conservative Catholic society, but urban institutions and a discreet scene; safest big city by crime statistics."),
        ("la libertad", "Trujillo: northern conservative coastal city; modest scene; crime rates elevated."),
        ("piura", "Piura: the most Catholic-conservative north (Opus Dei university influence); low salience."),
        ("lambayeque", "Chiclayo: northern traditional; low salience."),
        ("junín", "Huancayo: Andean commercial hub; conservative highland culture."),
        ("puno", "Puno/Lake Titicaca: most traditional Aymara/Quechua region — highland community conservatism strongest in Peru; tourism (Copacabana) small."),
        ("ayacucho", "Ayacucho: post-war (Shining Path era) society with strong church-traditional culture; conservative."),
        ("apurímac", "", ),
        ("apur", "Andean highland; among Peru's most traditional provinces."),
        ("huancavelica", "Poorest, most traditional highland region."),
        ("cajamarca", "Northern highlands; conservative; mining-conflict politics."),
        ("ancash", "Huaraz trekking-tourism economy gives foreigner-normalization; coastal Chimbote rougher."),
        ("ica", "Ica/Nazca/Paracas: desert tourism corridor; conservative small cities."),
        ("tacna", "Tacna: Chile-border; conservative commercial city."),
        ("tumbes", "Ecuador-border north; low salience."),
        ("loreto", "Iquitos: Amazon metropolis — frontier tolerance-of-eccentricity culture, rubber-boom cosmopolitan legacy; general crime high; small scene."),
        ("ucayali", "Pucallpa: Amazon frontier; shipibo indigenous culture; general lawlessness moderate."),
        ("san mart", "Tarapoto/Moyobamba: Amazonian high-jungle — Tarapoto is notably the most documented trans-community presence in Peru's regions (local activism since the 2000s); frontier society."),
        ("madre de dios", "Madre de Dios gold-frontier: Peru's most lawless region (human-trafficking corridor documented); danger is general."),
        ("amazonas", "Northern cloud-forest; traditional; low salience."),
        ("huánuco", "Huánuco: central highland-jungle transition; conservative."),
        ("huanuco", "Huánuco: central highland-jungle transition; conservative."),
        ("pasco", "Mining highland; traditional."),
        ("moquegua", "Small southern mining region; orderly, conservative."),
    ],
    "CHL": [
        ("valpara", "Valparaíso: Chile's bohemian port — the country's most artistically nonconforming city culture, large student population (UV/PUCV), documented trans organizing; port roughness is crime-general, not gender-targeted; Viña del Mar adjacent resort normality."),
        ("metropolitana", "Santiago (Bellavista/Lastarria): Latin America's second-most-institutionalized scene after Buenos Aires — MOVILH and Fundación Iguales headquartered here, Pride large, municipal protections in Providencia/Santiago Centro; 7-million anonymity; metro police functional."),
        ("antofagasta", "Antofagasta: mining north — transient-worker economy, money-cosmopolitanism; conservative small-city culture outside mining camps."),
        ("coquimbo", "La Serena/Coquimbo: tourism coast; modest conservative; low salience."),
        ("atacama", "Copiapó mining north; low salience."),
        ("tarapac", "Iquique: northern border port — zofri free-zone commerce, Peruvian/Bolivian migrant mix; northern conservatism but border permeability; crime elevated."),
        ("arica", "Arica: extreme north border; small-city conservatism; tourism modest."),
        ("del b", "Biobío/Concepción: Chile's second metro — university culture (UdeC) historically progressive, but Biobío's industrial/forest towns are socially traditional; Concepción scene organized and visible."),
        ("araucan", "La Araucanía: Mapuche-conflict region — militarized rural zones, state-of-emergency legacy; Temuco city modest scene; the danger is conflict-general; Mapuche traditional culture strongly gender-binary."),
        ("los r", "Los Ríos/Valdivia: university-town liberalism (UACh) in a conservative lake region; low salience."),
        ("los lagos", "Los Lagos/Puerto Montt: German-settlement conservative south; Chiloé island culture deeply Catholic-traditional (documented conservatism); Patagonia tourism envelope in the south."),
        ("magallanes", "Magallanes/Punta Arenas: Patagonian end-of-the-world society — small, close-knit, windswept; historically rough-frontier tolerance of eccentricity; lowest social salience in Chile; institutions orderly."),
        ("libertador", "O'Higgins/Rancagua: agricultural conservative heartland; low salience."),
        ("maule", "Maule/Talca: Chile's most rural-Catholic region (alongside Biobío interior); conservative; low salience."),
        ("uble", "Ñuble/Chillán: agricultural conservative; low salience."),
        ("ays", "Aysén/Coyhaique: Patagonian frontier — tiny population, tourism economy; low salience."),
    ],
    "KOR": [
        ("seoul", "Seoul: South Korea's entire visible scene — Itaewon Homo-hill (foreigner-friendly bar district), Jongno3-ga Korean gay district, Queer Culture Festival held annually under police protection against large Christian counter-protests; Seoul municipal government has been hostile to the festival (permit denials litigated) but national courts consistently protect it; 25-million anonymity; hormone access via private clinics exists."),
        ("incheon", "Incheon: Seoul-metro port spillover; no distinct scene; commuter anonymity."),
        ("gyeonggi", "Gyeonggi wraps Seoul — Suwon/Yongnan satellite cities share the metro's relative openness; provincial towns traditional."),
        ("busan", "Busan: Korea's second city — Haeundae tourism and port-history cosmopolitanism; scene discreet but organized; Busan Pride held (2015-present) against municipal obstruction; southeastern regional conservatism stronger than Seoul's."),
        ("daegu", "Daegu: Korea's most conservative major city — 2009 Pride attempt met with organized Christian mob blockade (documented), Daegu Queer Culture Festival 2023 clash with city government under Hong Joon-pyo; TBC/church political power strongest here; scene exists fully underground."),
        ("daejeon", "Daejeon: science-capital — KAIST student culture gives modest liberal pocket; city conservative overall."),
        ("gwangju", "Gwangju: Korea's progressive-democracy capital (May 18 legacy) — most politically liberal city, Pride held with municipal tolerance; Jeolla-region culture historically dissenting from conservative orthodoxy."),
        ("sejong", "Sejong: administrative new-town — bureaucratic, no scene, low salience."),
        ("jeju", "Jeju: self-governing island — tourism economy, distinct matriarchal-heritage culture (haenyeo), most socially relaxed Korean environment; Jeju Pride held; international residency highest."),
        ("gangwon", "Gangwon: mountain/border province — military-conservative culture (front-line service), tourism (Pyeongchang legacy); low salience."),
        ("north chungcheong", "Chungbuk: provincial middle; conservative; low salience."),
        ("south chungcheong", "Chungnam: provincial middle — 2020s human-rights-ordinance repeal battles documented here (conservative mobilization succeeded in gutting them); among the more hostile provincial climates."),
        ("north jeolla", "Jeonbuk: Jeolla progressive region; Jeonju modest scene; relatively tolerant climate."),
        ("south jeolla", "Jeonnam: most agricultural province; traditional; low salience."),
        ("north gyeongsang", "Gyeongbuk: Korea's conservative heartland (TK region, Daegu orbit, Gumi industrial Protestant belt) — strongest church-political anti-LGBT mobilization; Andong Confucian-tradition conservatism."),
        ("south gyeongsang", "Gyeongnam: southeastern industrial (Changwon/Gimhae) — conservative but urban-industrial; lower salience than Gyeongbuk."),
        ("ulsan", "Ulsan: Hyundai company-town — industrial conservatism; no scene."),
    ],
    "USA": [
        ("california", "California: America's scene capital (SF Castro, LA, West Hollywood municipal protections) — strongest state legal shield: sanctuary-state laws (SB 25/446) block out-of-state anti-trans enforcement, insurance mandates, explicit statutory protections; documented incidents occur but institutional response is the country's strongest."),
        ("new york", "New York: historic movement capital (Stonewall), vast NYC scene and anonymity; state Gender Expression Non-Discrimination Act and sanctuary provisions; upstate rural areas differ sharply from the metro."),
        ("massachusetts", "Massachusetts: first state to legalize same-sex marriage (2004), trans public-accommodations protection since 2016 upheld by referendum (voters kept it 68%); Boston scene institutional; the strongest durable consensus protection in the US."),
        ("minnesota", "Minnesota: trans-refuge-state law (2023 executive order + statute) — strongest legal shield in the country (non-cooperation with out-of-state warrants/extradition for gender-affirming care); Twin Cities scene deep (first Pride outside NYC historically); Minnesota also hosts the country's largest Somali-trans-woman community with documented organizing."),
        ("washington", "Washington: strong protections, Seattle scene, sanctuary provisions; east of the Cascades (rural WA) is politically another country."),
        ("illinois", "Illinois: Chicago's scene is among the world's largest; state protections strong (2021 trans-health shelter provisions); downstate Illinois conservative."),
        ("colorado", "Colorado: Denver scene, explicit constitutional-amendment protection (Amendment 64-adjacent equality jurisprudence), 2023 club-shooting (Colorado Springs) met with strong institutional response; mountain-west libertarian streak."),
        ("oregon", "Oregon: Portland scene, strong state protections, sanctuary history; rural eastern Oregon hosts documented secession movements."),
        ("maryland", "Maryland: 2023 Trans Safety Act; Baltimore/DC-orbit scene; conservative Eastern Shore and western counties."),
        ("connecticut", "Connecticut: consistently top-ranked protections; small-state institutional density near NYC metro."),
        ("new jersey", "New Jersey: strong protections, Asbury Park scene, Newark institutional base; dense anonymity near NYC/Philly."),
        ("vermont", "Vermont: first state constitutional same-sex union (civil unions 2000); small-population progressive consensus; rural tolerance documented as high."),
        ("new mexico", "New Mexico: Santa Fe/ABQ relatively open; strong state protections; conservative rural counties."),
        ("rhode island", "Rhode Island: small-state protections strong; Providence scene modest."),
        ("hawaii", "Hawaiʻi: mahu culture is a documented indigenous third-gender tradition with real social standing; state protections strong; tourism economy; close-knit society where anonymity is limited but acceptance culturally rooted."),
        ("maine", "Maine: protections strong (2000s referendum battles won); Portland scene; rural conservative."),
        ("new hampshire", "New Hampshire: legal protections exist but the state legislature has been a documented battleground (2020s bathroom/health bills); libertarian streak cuts both ways."),
        ("nevada", "Nevada: constitutional gender-identity amendment (2022 voter-approved); Las Vegas tourism envelope gives real permissiveness; rural counties conservative."),
        ("delaware", "Delaware: protections solid; small-state; modest scene."),
        ("district of columbia", "Washington DC: America's institutional LGBT capital — federal city, embassy presence, Dupont/Logan/U Street scenes, strongest municipal protections; but DC crime dynamics affect street-level safety independent of LGBT status."),
        ("virginia", "Virginia: post-2020 Democratic-trifecta passed broad protections (Virginia Values Act 2020); Northern Virginia (DC orbit) among America's most protected environments; south-side/rural Virginia traditional."),
        ("pennsylvania", "Pennsylvania: patchwork — Philadelphia and Pittsburgh have strong city ordinances and deep scenes (Philadelphia's trans-health access documented strong); state-level protections via commission interpretation; central-PA (Lancaster/Altoona) Amish-adjacent and Rust Belt conservative."),
        ("michigan", "Michigan: Detroit scene, 2023 Elliott-Larsen expansion added gender identity to state civil rights; western Michigan (Ottawa County) religious-conservative."),
        ("wisconsin", "Wisconsin: first state to ban orientation discrimination (1982) — gender identity still excluded from the statute (documented gap); Madison/Milwaukee progressive cities."),
        ("arizona", "Arizona: Phoenix/Tucson scenes, tribal-nation jurisdictions vary (Navajo Nation conservative); state legislature hostile (2020s bathroom bills, education restrictions) but metro governments protective; desert-libertarian culture."),
        ("georgia", "Georgia: Atlanta is the Black LGBT capital of America (documented institutional depth) with strong city ordinances; state government hostile (2020s legislation); rural Georgia deeply conservative."),
        ("north carolina", "North Carolina: HB2 (2016 bathroom bill) made it the national symbol of anti-trans legislation — state-level hostility documented and sustained; Charlotte/Raleigh/Durham metros protective by ordinance and culture; the state remains an active legislative battleground."),
        ("texas", "Texas: Houston/Dallas/Austin scenes are large (Austin notably progressive-island), but state government is America's most aggressive anti-trans legislator (2020s: bathroom bills repeated, drag restrictions, trans-health felony prosecutions of parents documented); state police power is real — Texas differs from paper-hostile states because enforcement machinery here is active."),
        ("florida", "Florida: Miami/Wilton Manors scenes among America's largest, tourism economy envelope real; but DeSantis-era state government enacted the nation's most-enforced restrictions (Disney fight, drag-ban attempts with documented first arrest — charges dismissed, bathroom enforcement in state buildings); Florida combines maximum visibility with maximum state-level targeting."),
        ("ohio", "Ohio: Columbus/Cleveland/Cincinnati scenes; state-level 2020s hostility (bathroom bills introduced, youth-care bans litigated); suburban-rural conservative."),
        ("indiana", "Indiana: RFRA-2015 made it the first state to lose national corporate events over LGBT discrimination; Indianapolis scene modest; state politics among the most consistently hostile in the Midwest."),
        ("tennessee", "Tennessee: America's anti-trans legislative epicenter — first state to pass an adult-drag ban (2023, struck in part by courts), Nashville Pride met with organized counter-mobilization, Memphis/Nashville scenes persist under the country's most aggressive legislative environment; rural TN among the most conservative."),
        ("missouri", "Missouri: 2023 attorney-general emergency restrictions on trans care (litigated), St. Louis/KC scenes modest; state hostile."),
        ("iowa", "Iowa: 2019 removed gender-identity from state civil-rights code protections for bathrooms — documented rollback; Des Moines modest scene; rural Iowa conservative-evangelical."),
        ("kansas", "Kansas: 2023 trans-bathroom/lockerroom restrictions enacted; but Kansas voters famously rejected an anti-abortion amendment — split political culture; KC-Kansas modest scene."),
        ("kentucky", "Kentucky: 2022 bathroom restrictions + youth-care ban (veto overridden — first override of its kind); Louisville/Lexington modest scenes; Appalachian conservatism."),
        ("louisiana", "Louisiana: America's harshest combination — 2025 first-in-nation law requiring trans people to use bathrooms of birth-sex in public accommodations with criminal exposure, documented first prosecution, highest per-capita homicide rate, New Orleans' visible French-Quarter scene persists in paradox; enforcement reality plus victim-prosecution precedent put it at the national floor."),
        ("mississippi", "Mississippi: religious-freedom-restoration act (2016) licensed discrimination; deepest rural poverty; Jackson modest; effectively no protective infrastructure."),
        ("alabama", "Alabama: youth-care ban litigated to the Supreme Court; Birmingham modest scene; Deep South conservative institutions."),
        ("arkansas", "Arkansas: first state to ban youth gender care (2021, struck then revived litigation); Little Rock modest; deeply conservative."),
        ("oklahoma", "Oklahoma: aggressive 2020s legislation (bathroom, education, drag); Tulsa/OKC modest scenes; conservative."),
        ("west virginginia", "", ),
        ("west virginia", "West Virginia: youth-care ban; poorest state institutions; Charleston modest; socially traditional."),
        ("south carolina", "South Carolina: 2020s bathroom and care restrictions; Charleston's tourism envelope and historic scene are the exception; Upstate conservative."),
        ("idaho", "Idaho: strictest documented bathroom regime (criminal facility ban reaching private businesses, felony on second offense — partially court-blocked but operative where no gender-neutral option exists), four legislative rounds 2023-2026; Boise has a surprisingly organized scene (city protections) surrounded by the most legislatively hostile state culture."),
        ("montana", "Montana: youth-care ban litigated (struck by state court 2024 — documented institutional check); Billings/Bozeman modest scenes; libertarian-west streak."),
        ("wyoming", "Wyoming: smallest population; 2024 first-of-kind adult-care restrictions (subsequently struck); low salience, low infrastructure."),
        ("utah", "Utah: LDS institutional culture shapes everything — but Utah's legislative approach is paternalistic-protectionist rather than punitive (2015 nondiscrimination-for-religious-liberty trade, bathroom law targeting only schools, youth-care ban); Salt Lake City has a real scene (city protections); rural Utah is the most religiously governed environment in the US."),
        ("alaska", "Alaska: frontier individualism; Anchorage modest scene; 2020s ballot initiatives against trans athletes (failed narrowly); low salience."),
        ("nebraska", "Nebraska: 2023 legislative restrictions passed after filibuster drama; Omaha/Lincoln modest scenes; conservative."),
        ("south dakota", "South Dakota: first state to attempt youth-care ban (2020, vetoed; passed 2022); small population, low salience, conservative."),
        ("north dakota", "North Dakota: 2023 bathroom/care restrictions; tiny scene; conservative."),
    ],
}
KNOWLEDGE["IND"] = [(p, n) for p, n in KNOWLEDGE["IND"] if n]
KNOWLEDGE["ESP"] = [(p, n) for p, n in KNOWLEDGE["ESP"] if n]
KNOWLEDGE["COL"] = [(p, n) for p, n in KNOWLEDGE["COL"] if n]
KNOWLEDGE["ARG"] = [(p, n) for p, n in KNOWLEDGE["ARG"] if n]
KNOWLEDGE["PER"] = [(p, n) for p, n in KNOWLEDGE["PER"] if n]
KNOWLEDGE["TUR"] = [(p, n) for p, n in KNOWLEDGE["TUR"] if n]
KNOWLEDGE["IDN"] = [(p, n) for p, n in KNOWLEDGE["IDN"] if n]
KNOWLEDGE["USA"] = [(p, n) for p, n in KNOWLEDGE["USA"] if n]
KNOWLEDGE["CHL"] = [(p, n) for p, n in KNOWLEDGE["CHL"] if n]


def apply(admin1: dict) -> tuple[int, int]:
    n_specific = n_default = 0
    for sid, rec in admin1.items():
        iso = rec.get("iso3")
        if iso not in KNOWLEDGE:
            continue
        lname = rec.get("name", "").lower()
        note = None
        for pat, nt in KNOWLEDGE[iso]:
            if pat and pat in lname:
                note = nt
                break
        if note:
            rec["modelContext"] = note
            n_specific += 1
        else:
            rec["modelContext"] = DEFAULT_NOTE
            n_default += 1
    return n_specific, n_default


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--admin1-file", default=str(ROOT / "data" / "admin1.json"))
    args = ap.parse_args()

    p = Path(args.admin1_file)
    admin1 = json.loads(p.read_text(encoding="utf-8"))
    n_specific, n_default = apply(admin1)
    print(f"modelContext written: {n_specific} specific · {n_default} default · "
          f"{len(KNOWLEDGE)} country tables")
    if args.dry_run:
        return 0
    tmp = p.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(admin1, indent=1, ensure_ascii=False), encoding="utf-8")
    tmp.replace(p)
    print(f"wrote {p}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
