#!/usr/bin/env python3
"""W2 four-field split for batch s022 (8 BRA/IND admin1 records).
Visible fields derive from current text + source claims only (restructure, no research).
Blind mirrors are substitution-only derivations (LANE_SPECS rules 7/7e).
MERGE-FIRST write after each record; keep other whos.
Self-gate: tools/check_blind.py --file data/split_out/s022.json
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "data/split_out" / "s022.json"
BATCH_WHOS = ["BRA/Tocantins", "BRA/Espirito Santo", "BRA/Mato Grosso do Sul",
              "BRA/Sao Paulo", "BRA/Parana", "BRA/Rio Grande do Sul",
              "IND/Puducherry", "IND/Nāgāland"]

RECORDS = [
# ---------------------------------------------------------------- BRA/Tocantins
{
 "who": "BRA/Tocantins",
 "summary": "<p>Tocantins stands entirely under the nationally uniform framework a visitor meets in any Brazilian state: marriage equality since 2013, name and gender-marker change at the registry without surgery since 2018, homophobia and transphobia criminalised as equivalent to racism by the Supreme Court in 2019, and non-binary civil-registry amendments allowed by a 2025 superior-court ruling — protections built by the courts rather than statute. Same-sex marriage is the marriage/partner-travel baseline for a visiting couple, with full legal effect since 2013.</p>\n<p>Practical risk is set by the national profile: the country has one of the highest rates of violence against sexual and gender minorities, particularly trans people, and that profile, not any local divergence, sets the state's risk. A law-firm guide records that the legal rights are identical nationwide while major cities are broadly welcoming and smaller cities and rural areas may present more social friction — a distinction that reaches through Tocantins as elsewhere.</p>",
 "tangentialFactors": "<p>National policy turbulence: repeal efforts active in Congress bear on the stability of protections that were built by the courts rather than statute, so the visitor-facing framework, though in force, sits under active legislative challenge. No litigation flux or comparison with neighbouring divisions is documented in the dossier for this state.</p>",
 "localsOnly": "<p>Resident-facing signal: the 2024 municipal elections saw openly LGBTQ candidacies running into the thousands — over 3,000 candidates nationally — evidencing political visibility at local level; no resident discrimination data specific to Tocantins is documented in the dossier.</p>",
 "outOfScopeNotes": "<p>No Tocantins-specific statute, ordinance or enforcement pattern is on file, so the assessment rests on the national framework and the national violence profile rather than state-level data. No border-screening or visitor-document practice specific to the state is recorded in the dossier; the registry-based name and gender-marker change is the only document-relevant provision, and it is national. Marriage and partner-travel relevance rests on the national same-sex marriage position, with no local counterpart documented.</p>",
 "blindSummary": "<p>This state/province stands entirely under the nationally uniform framework a visitor meets in any state/province of the parent nation: marriage equality since 2013, name and gender-marker change at the registry without surgery since 2018, homophobia and transphobia criminalised as equivalent to racism by the national court in 2019, and non-binary civil-registry amendments allowed by a 2025 superior-court ruling — protections built by the courts rather than statute. Same-sex marriage is the marriage/partner-travel baseline for a visiting couple, with full legal effect since 2013.</p>\n<p>Practical risk is set by the national profile: the country has one of the highest rates of violence against sexual and gender minorities, particularly trans people, and that profile, not any local divergence, sets the risk in this state/province. A law-firm guide records that the legal rights are identical nationwide while major cities are broadly welcoming and smaller cities and rural areas may present more social friction — a distinction that reaches through this state/province as elsewhere.</p>",
 "blindTangential": "<p>National policy turbulence: repeal efforts active in the elected legislature bear on the stability of protections that were built by the courts rather than statute, so the visitor-facing framework, though in force, sits under active legislative challenge. No litigation flux or comparison with neighbouring divisions is documented in the dossier for this state/province.</p>",
 "blindLocalsOnly": "<p>Resident-facing signal: the 2024 municipal elections saw openly LGBTQ candidacies running into the thousands — thousands of candidates nationally — evidencing political visibility at local level; no resident discrimination data specific to this state/province is documented in the dossier.</p>",
 "blindOutOfScope": "<p>No state/province-specific statute, ordinance or enforcement pattern is on file, so the assessment rests on the national framework and the national violence profile rather than state/province-level data. No border-screening or visitor-document practice specific to the state/province is recorded in the dossier; the registry-based name and gender-marker change is the only document-relevant provision, and it is national. Marriage and partner-travel relevance rests on the national same-sex marriage position, with no local counterpart documented.</p>",
 "blindSourceSummaries": [
  "Country-framework page (revised through 2026): same-sex marriage legal nationwide via a national court resolution of 14 May 2013 (14-1 vote), adoption since 2010 (full rights 2015), and gender-marker change without surgery, hormones or diagnosis since the national highest-court ruling of 1 March 2018. On 13 June 2019 the national highest court held discrimination and violence on grounds of sexual orientation or gender identity a crime equivalent to racism under a 1989 law, punishable by imprisonment and fines. No third-gender option nationwide, but civil-registry 'non-binary/unspecified' entries have been possible since 2020 and a 6 May 2025 national high-court ruling allows neutral-gender registry rectification as precedent. First transgender national legislators were elected in 2022.",
  "International rights organisation country report, last updated 12 March 2026: the nation's legal advances for LGBTIQ people are significant but face repeal pressure in a conservative elected legislature. The nation retains one of the world's highest rates of violence against sexual and gender minorities, particularly trans people. Gender-marker change proceeds by self-determination and trans voters may register under lived name and identity even before documents are updated. Thousands of openly LGBTQ candidates ran in the 2024 municipal elections, evidencing local political visibility.",
  "Law-firm guide for expatriates (updated April 2026): the nation has among the most progressive protections on paper — same-sex marriage (2013 resolution), joint adoption, name and gender-marker change without surgery, and homophobia/transphobia criminalised as equivalent to racism (13 June 2019, imprisonment 1-5 years). Enforcement is uneven in practice: major cities are broadly welcoming with established legal infrastructure, while smaller cities and rural areas may present more social friction despite identical legal rights."
 ],
 "notes": "Four-field split from current_summary plus the three source claims: court-built protections and practical-safety profile to summary; Congress repeal-pressure context to tangentialFactors; candidate-visibility data to localsOnly; no-local-data and documents-scope caveats to outOfScopeNotes."
},
# ---------------------------------------------------------------- BRA/Espirito Santo
{
 "who": "BRA/Espirito Santo",
 "summary": "<p>Espirito Santo stands under the uniform national framework: same-sex marriage legal nationwide since May 2013 (binding resolution on all civil registries), name and gender-marker change without surgery, and discrimination on sexual orientation or gender identity a crime equivalent to racism since the 2019 national court ruling. No state-specific law or enforcement pattern differentiates the unit for a visitor.</p>\n<p>Practical-safety reading for a traveler: the dossier's key structural caveat applies — at least 68% of killings occur outside state capitals, in interior towns — so interior exposure, not the capital, carries the documented risk, and a low recorded state count can hide interior exposure.</p>",
 "tangentialFactors": "<p>National-policy turbulence: the 2019 national court ruling makes discrimination and hate crimes based on sexual orientation or gender identity criminally punishable, though no specific anti-discrimination statute exists and the elected legislature carries repeal efforts; a 2023 national court ruling allowed nonbinary people to amend civil records, while intersex people lack specific protections. Per the record's freshness review the uniform framework stood confirmed current as of September 2026.</p>",
 "localsOnly": "<p>Resident data: ANTRA's 2025 state tally records 2 killings in the unit — a low absolute count; the recorded killings are of local residents, so the tally is resident-facing violence data rather than a visitor incident series, and no resident discrimination data beyond the tally is on file.</p>",
 "outOfScopeNotes": "<p>No state-specific law or enforcement pattern was found, and the record's freshness review notes the cited sources are country-level, leaving state-specific claims unanchored to state-level documentation. No state-specific border-screening or visitor-document practice is recorded in the dossier, and the tally's low count may hide interior exposure given the structural caveat.</p>",
 "blindSummary": "<p>This state/province stands under the uniform national framework: same-sex marriage legal nationwide since May 2013 (binding resolution on all civil registries), name and gender-marker change without surgery, and discrimination on sexual orientation or gender identity a crime equivalent to racism since the 2019 national court ruling. No state/province-specific law or enforcement pattern differentiates the unit for a visitor.</p>\n<p>Practical-safety reading for a traveler: the dossier's key structural caveat applies — at least 68% of killings occur outside state/province capitals, in interior towns — so interior exposure, not the capital, carries the documented risk, and a low recorded state/province count can hide interior exposure.</p>",
 "blindTangential": "<p>National-policy turbulence: the 2019 national court ruling makes discrimination and hate crimes based on sexual orientation or gender identity criminally punishable, though no specific anti-discrimination statute exists and the elected legislature carries repeal efforts; a 2023 national court ruling allowed nonbinary people to amend civil records, while intersex people lack specific protections. Per the record's freshness review the uniform framework stood confirmed current as of September 2026.</p>",
 "blindLocalsOnly": "<p>Resident data: the 2025 state/province tally records 2 killings in the unit — a low absolute count; the recorded killings are of local residents, so the tally is resident-facing violence data rather than a visitor incident series, and no resident discrimination data beyond the tally is on file.</p>",
 "blindOutOfScope": "<p>No state/province-specific law or enforcement pattern was found, and the record's freshness review notes the cited sources are country-level, leaving state/province-specific claims unanchored to state/province-level documentation. No state/province-specific border-screening or visitor-document practice is recorded in the dossier, and the tally's low count may hide interior exposure given the structural caveat.</p>",
 "blindSourceSummaries": [
  "National framework page: same-sex marriage legal nationwide since May 2013 (binding resolution for all civil registries in a 14-1 vote); on 13 June 2019 the national highest court ruled discrimination on sexual orientation or gender identity a crime equivalent to racism with imprisonment and fines; adoption rights since 2015; LGB people serve openly in the military; explicit national discrimination protections since 2019. The uniform framework a visitor stands under in any state/province of the parent nation.",
  "2026 rights-organisation status: a 2019 national court ruling makes discrimination and hate crimes based on sexual orientation and gender identity criminally punishable, though no specific anti-discrimination statute exists and the elected legislature has repeal efforts; a 2023 national court ruling allowed nonbinary people to amend civil records; intersex people lack specific protections. Framework applies uniformly across the nation.",
  "Expat-focused legal guide (updated 5 April 2026): same-sex marriage available nationwide since 2013 (binding resolution), spousal-visa equality, joint adoption, and name/gender-marker changes without surgery; the 13 June 2019 ruling makes homophobia/transphobia crimes equivalent to racism; larger cities have legal infrastructure, while smaller cities and rural areas carry more social friction."
 ],
 "notes": "Split from current_summary, three source claims and freshness_all: framework protections and interior-exposure reading to summary; the 2-killings tally to localsOnly as resident data; repeal pressure and freshness confirmation to tangentialFactors; country-level-sources and unanchored-claims caveats to outOfScopeNotes."
},
# ---------------------------------------------------------------- BRA/Mato Grosso do Sul
{
 "who": "BRA/Mato Grosso do Sul",
 "summary": "<p>Mato Grosso do Sul stands under Brazil's uniform national framework — same-sex marriage nationwide since May 2013 and discrimination on sexual orientation or gender identity a crime equivalent to racism since June 2019 — and no state-specific law or enforcement pattern differentiates the unit for a visitor.</p>\n<p>The practical risk for a traveler sits in geography rather than the state average: interior-versus-capital geography, not the state average, is where the risk actually sits.</p>",
 "tangentialFactors": "<p>Structural context: federally administered indigenous lands and quilombola territories with parallel community authority sit inside this unit, colouring a visit where community authority operates; no trans-specific evidence from those lands is sourced in the dossier. National-policy context: discrimination and hate crimes based on sexual orientation or gender identity are criminally punishable under the 2019 national court ruling though no specific anti-discrimination statute exists, and the elected legislature carries repeal efforts bearing on the framework's stability; no litigation flux or comparison with neighbouring divisions beyond the uniform framework is documented.</p>",
 "localsOnly": "<p>Resident-side data: the 2025 state tally (ANTRA) records 2 killings in the unit, and the recorded killings are of local residents — resident violence data rather than a visitor incident series; no resident discrimination data beyond the tally is on file.</p>",
 "outOfScopeNotes": "<p>No state-specific law or enforcement pattern was found, leaving the unit assessed on the national framework alone. No trans-specific evidence from the indigenous or community lands was sourced, so their bearing on visitor risk is unresolved. No state-specific border-screening or visitor-document practice is recorded in the dossier.</p>",
 "blindSummary": "<p>This state/province stands under the uniform national framework of the parent nation — same-sex marriage nationwide since May 2013 and discrimination on sexual orientation or gender identity a crime equivalent to racism since June 2019 — and no state/province-specific law or enforcement pattern differentiates the unit for a visitor.</p>\n<p>The practical risk for a traveler sits in geography rather than the state/province average: interior-versus-capital geography, not the state/province average, is where the risk actually sits.</p>",
 "blindTangential": "<p>Structural context: lands administered by the national government and historic community lands with parallel community authority sit inside this unit, colouring a visit where community authority operates; no trans-specific evidence from those lands is sourced in the dossier. National-policy context: discrimination and hate crimes based on sexual orientation or gender identity are criminally punishable under the 2019 national court ruling though no specific anti-discrimination statute exists, and the elected legislature carries repeal efforts bearing on the framework's stability; no litigation flux or comparison with neighbouring divisions beyond the uniform framework is documented.</p>",
 "blindLocalsOnly": "<p>Resident-side data: the 2025 state/province tally records 2 killings in the unit, and the recorded killings are of local residents — resident violence data rather than a visitor incident series; no resident discrimination data beyond the tally is on file.</p>",
 "blindOutOfScope": "<p>No state/province-specific law or enforcement pattern was found, leaving the unit assessed on the national framework alone. No trans-specific evidence from the indigenous or historic community lands was sourced, so their bearing on visitor risk is unresolved. No state/province-specific border-screening or visitor-document practice is recorded in the dossier.</p>",
 "blindSourceSummaries": [
  "National framework page: same-sex marriage legal nationwide since May 2013 (binding resolution for all civil registries in a 14-1 vote); on 13 June 2019 the national highest court ruled discrimination on sexual orientation or gender identity a crime equivalent to racism with imprisonment and fines; adoption rights since 2015; LGB people serve openly in the military; explicit national discrimination protections since 2019. The uniform framework a visitor stands under in any state/province of the parent nation.",
  "2026 rights-organisation status: a 2019 national court ruling makes discrimination and hate crimes based on sexual orientation and gender identity criminally punishable, though no specific anti-discrimination statute exists and the elected legislature has repeal efforts; a 2023 national court ruling allowed nonbinary people to amend civil records; intersex people lack specific protections. Framework applies uniformly across the nation."
 ],
 "notes": "Split from current_summary plus two source claims: uniform framework and interior-geography reading to summary; indigenous/quilombola structural context and repeal pressure to tangentialFactors; 2-killings tally to localsOnly; unanchored-evidence and no-visitor-data caveats to outOfScopeNotes."
},
# ---------------------------------------------------------------- BRA/Sao Paulo
{
 "who": "BRA/Sao Paulo",
 "summary": "<p>Sao Paulo sits under the uniform national framework — same-sex marriage since May 2013, name and gender-marker change without surgery, and discrimination on sexual orientation or gender identity a crime equivalent to racism since June 2019 — with no state-specific enforcement divergence recorded for visitors.</p>\n<p>The practical-safety picture is mixed and set by resident-violence data rather than visitor incidents: the unit led the national ranking in 2024 with 16 killings of travestis and trans people, then fell to 4 recorded killings in 2025, out of the top group. The country's dominant geographic pattern applies here: at least 68% of the 2024 killings (83 of 122) happened outside state capitals, in interior cities, so a traveler's risk sits in the interior rather than the capital.</p>",
 "tangentialFactors": "<p>National-policy context: discrimination and hate crimes based on sexual orientation or gender identity are criminally punishable under the 2019 national court ruling though no specific anti-discrimination statute exists, and the elected legislature carries repeal efforts bearing on the framework's stability; no litigation flux or comparison with neighbouring divisions is documented in the dossier for this state.</p>",
 "localsOnly": "<p>The recorded killings are of local trans residents - the 2024 national victim profile is majority young, Black and poor - rather than visitors; the protective federal machinery (name/gender change, hate-crime doctrine) is likewise resident-facing administrative law.</p>",
 "outOfScopeNotes": "<p>The killings tallies are resident data, not a visitor incident series, so their direct bearing on visitor risk is inferential; no state-specific border-screening or visitor-document practice is recorded in the dossier, and no partner-travel provision beyond national same-sex marriage is documented.</p>",
 "blindSummary": "<p>This state/province sits under the uniform national framework — same-sex marriage since May 2013, name and gender-marker change without surgery, and discrimination on sexual orientation or gender identity a crime equivalent to racism since June 2019 — with no state/province-specific enforcement divergence recorded for visitors.</p>\n<p>The practical-safety picture is mixed and set by resident-violence data rather than visitor incidents: the unit led the national ranking in 2024 with 16 killings of travestis and trans people, then fell to 4 recorded killings in 2025, out of the top group. The country's dominant geographic pattern applies here: at least 68% of the 2024 killings (83 of 122) happened outside state/province capitals, in interior cities, so a traveler's risk sits in the interior rather than the capital.</p>",
 "blindTangential": "<p>National-policy context: discrimination and hate crimes based on sexual orientation or gender identity are criminally punishable under the 2019 national court ruling though no specific anti-discrimination statute exists, and the elected legislature carries repeal efforts bearing on the framework's stability; no litigation flux or comparison with neighbouring divisions is documented in the dossier for this state/province.</p>",
 "blindLocalsOnly": "<p>The recorded killings are of local trans residents — the 2024 national victim profile is majority young, Black and poor — rather than visitors; the protective national machinery (name/gender change, hate-crime doctrine) is likewise resident-facing administrative law.</p>",
 "blindOutOfScope": "<p>The killings tallies are resident data, not a visitor incident series, so their direct bearing on visitor risk is inferential; no state/province-specific border-screening or visitor-document practice is recorded in the dossier, and no partner-travel provision beyond national same-sex marriage is documented.</p>",
 "blindSourceSummaries": [
  "National framework page: same-sex marriage legal nationwide since May 2013 (binding resolution for all civil registries in a 14-1 vote); on 13 June 2019 the national highest court ruled discrimination on sexual orientation or gender identity a crime equivalent to racism with imprisonment and fines; adoption rights since 2015; LGB people serve openly in the military; explicit national discrimination protections since 2019. The uniform framework a visitor stands under in any state/province of the parent nation.",
  "2026 rights-organisation status: a 2019 national court ruling makes discrimination and hate crimes based on sexual orientation and gender identity criminally punishable, though no specific anti-discrimination statute exists and the elected legislature has repeal efforts; a 2023 national court ruling allowed nonbinary people to amend civil records; intersex people lack specific protections. Framework applies uniformly across the nation.",
  "Expat-focused legal guide (updated 5 April 2026): same-sex marriage available nationwide since 2013 (binding resolution), spousal-visa equality, joint adoption, and name/gender-marker changes without surgery; the 13 June 2019 ruling makes homophobia/transphobia crimes equivalent to racism; larger cities have legal infrastructure, while smaller cities and rural areas carry more social friction."
 ],
 "notes": "current_localsOnly preserved verbatim in localsOnly (em-dashes normalised; federal->national in the blind mirror); killings tallies and interior-geography risk kept in summary with the resident-data nature flagged; congressional repeal context to tangentialFactors; inferential-basis caveat to outOfScopeNotes."
},
# ---------------------------------------------------------------- BRA/Parana
{
 "who": "BRA/Parana",
 "summary": "<p>Parana is assessed at the national score: the country dossier that covered this division identified no deviation from the national position material enough to score separately (within ±0.02). A visitor therefore stands under the uniform national framework — same-sex marriage since May 2013, name and gender-marker change without surgery, and discrimination on sexual orientation or gender identity criminalised since June 2019.</p>",
 "tangentialFactors": "<p>The dossier-level finding recorded for this division is the comparative assessment itself: no deviation from the national position material enough to score separately emerged, and no national-policy turbulence or litigation flux beyond the uniform framework is documented in the dossier for this division.</p>",
 "localsOnly": "<p>No resident-specific statute, enforcement series, or discrimination data specific to this division is recorded in the dossier; the uniform national framework claims are the only sourced content.</p>",
 "outOfScopeNotes": "<p>The assessment rests on the country dossier's no-material-deviation finding bounded by the ±0.02 threshold; no division-specific law, enforcement pattern or incident data is on file, and the absence of a deviation signal is not proof of no local practice. No border-screening or visitor-document practice specific to the division is recorded in the dossier.</p>",
 "blindSummary": "<p>This state/province is assessed at the national score: the country dossier that covered this division identified no deviation from the national position material enough to score separately (within ±0.02). A visitor therefore stands under the uniform national framework — same-sex marriage since May 2013, name and gender-marker change without surgery, and discrimination on sexual orientation or gender identity criminalised since June 2019.</p>",
 "blindTangential": "<p>The dossier-level finding recorded for this division is the comparative assessment itself: no deviation from the national position material enough to score separately emerged, and no national-policy turbulence or litigation flux beyond the uniform framework is documented in the dossier for this division.</p>",
 "blindLocalsOnly": "<p>No resident-specific statute, enforcement series, or discrimination data specific to this division is recorded in the dossier; the uniform national framework claims are the only sourced content.</p>",
 "blindOutOfScope": "<p>The assessment rests on the country dossier's no-material-deviation finding bounded by the ±0.02 threshold; no division-specific law, enforcement pattern or incident data is on file, and the absence of a deviation signal is not proof of no local practice. No border-screening or visitor-document practice specific to the division is recorded in the dossier.</p>",
 "blindSourceSummaries": [
  "National framework page: same-sex marriage legal nationwide since May 2013 (binding resolution for all civil registries in a 14-1 vote); on 13 June 2019 the national highest court ruled discrimination on sexual orientation or gender identity a crime equivalent to racism with imprisonment and fines; adoption rights since 2015; LGB people serve openly in the military; explicit national discrimination protections since 2019. The uniform framework a visitor stands under in any state/province of the parent nation.",
  "2026 rights-organisation status: a 2019 national court ruling makes discrimination and hate crimes based on sexual orientation and gender identity criminally punishable, though no specific anti-discrimination statute exists and the elected legislature has repeal efforts; a 2023 national court ruling allowed nonbinary people to amend civil records; intersex people lack specific protections. Framework applies uniformly across the nation."
 ],
 "notes": "Thin record: country-dossier no-deviation finding kept as the comparative assessment in tangentialFactors; national framework protections in summary; no-division-data caveats to localsOnly and outOfScopeNotes."
},
# ---------------------------------------------------------------- BRA/Rio Grande do Sul
{
 "who": "BRA/Rio Grande do Sul",
 "summary": "<p>Rio Grande do Sul is assessed at the national score: the country dossier that covered this division identified no deviation from the national position material enough to score separately (within ±0.02). A visitor therefore stands under the uniform national framework — same-sex marriage since May 2013, name and gender-marker change without surgery, and discrimination on sexual orientation or gender identity criminalised since June 2019; the law-firm guide adds that the legal rights are identical nationwide while larger cities carry legal infrastructure and smaller cities and rural areas more social friction.</p>",
 "tangentialFactors": "<p>The dossier-level finding recorded for this division is the comparative assessment itself: no deviation from the national position material enough to score separately emerged, and no national-policy turbulence or litigation flux beyond the uniform framework is documented in the dossier for this division.</p>",
 "localsOnly": "<p>No resident-specific statute, enforcement series, or discrimination data specific to this division is recorded in the dossier; the uniform national framework claims are the only sourced content.</p>",
 "outOfScopeNotes": "<p>The assessment rests on the country dossier's no-material-deviation finding bounded by the ±0.02 threshold; no division-specific law, enforcement pattern or incident data is on file, and the absence of a deviation signal is not proof of no local practice. No border-screening or visitor-document practice specific to the division is recorded in the dossier.</p>",
 "blindSummary": "<p>This state/province is assessed at the national score: the country dossier that covered this division identified no deviation from the national position material enough to score separately (within ±0.02). A visitor therefore stands under the uniform national framework — same-sex marriage since May 2013, name and gender-marker change without surgery, and discrimination on sexual orientation or gender identity criminalised since June 2019; the law-firm guide adds that the legal rights are identical nationwide while larger cities carry legal infrastructure and smaller cities and rural areas more social friction.</p>",
 "blindTangential": "<p>The dossier-level finding recorded for this division is the comparative assessment itself: no deviation from the national position material enough to score separately emerged, and no national-policy turbulence or litigation flux beyond the uniform framework is documented in the dossier for this division.</p>",
 "blindLocalsOnly": "<p>No resident-specific statute, enforcement series, or discrimination data specific to this division is recorded in the dossier; the uniform national framework claims are the only sourced content.</p>",
 "blindOutOfScope": "<p>The assessment rests on the country dossier's no-material-deviation finding bounded by the ±0.02 threshold; no division-specific law, enforcement pattern or incident data is on file, and the absence of a deviation signal is not proof of no local practice. No border-screening or visitor-document practice specific to the division is recorded in the dossier.</p>",
 "blindSourceSummaries": [
  "National framework page: same-sex marriage legal nationwide since May 2013 (binding resolution for all civil registries in a 14-1 vote); on 13 June 2019 the national highest court ruled discrimination on sexual orientation or gender identity a crime equivalent to racism with imprisonment and fines; adoption rights since 2015; LGB people serve openly in the military; explicit national discrimination protections since 2019. The uniform framework a visitor stands under in any state/province of the parent nation.",
  "2026 rights-organisation status: a 2019 national court ruling makes discrimination and hate crimes based on sexual orientation and gender identity criminally punishable, though no specific anti-discrimination statute exists and the elected legislature has repeal efforts; a 2023 national court ruling allowed nonbinary people to amend civil records; intersex people lack specific protections. Framework applies uniformly across the nation.",
  "Expat-focused legal guide (updated 5 April 2026): same-sex marriage available nationwide since 2013 (binding resolution), spousal-visa equality, joint adoption, and name/gender-marker changes without surgery; the 13 June 2019 ruling makes homophobia/transphobia crimes equivalent to racism; larger cities have legal infrastructure, while smaller cities and rural areas carry more social friction."
 ],
 "notes": "Same thin-dossier structure as Parana; the law-firm guide city/rural friction distinction folded into the visitor summary from the third source claim; no-division-data caveats to localsOnly and outOfScopeNotes."
},
# ---------------------------------------------------------------- IND/Puducherry
{
 "who": "IND/Puducherry",
 "summary": "<p>Puducherry is a union territory with a partial legislature: recognition and welfare policy for trans people is set principally by the federal government, and no Puducherry-specific statute, enforcement series or incident pattern is on file.</p>\n<p>The framework that governs it shifted sharply in March 2026: parliament passed an amendment removing the self-identification right affirmed by the 2014 Supreme Court ruling, restricting legal recognition to historically recognised communities (hijra/kinnar) and intersex people, and mandating medical certification for identity documents and for surgery; the medical-certification mandate is a direct documents consequence for a trans traveler whose papers now rest on that certification, and the change bears uniformly on every state and union territory, so it reaches visitors identically.</p>\n<p>Practical safety: a nationally recurring policing practice treats trans appearance as a suspicion category in transit spaces, evidenced by an August 2024 railway-platform groping complaint — a formal complaint was filed and intrusive questioning reported — reaching visitors through federal transport policing rather than any local law.</p>",
 "tangentialFactors": "<p>National policy turbulence: the March 2026 amendment passed over warnings from critics and a court-appointed advisory panel that it excludes many trans, non-binary and gender-fluid people, with protests following the vote in several cities; the human-rights reporting calls the amendment a major reversal of the 2014 rights position, and the change bears uniformly on every state and union territory including this division. No litigation flux or comparison with neighbouring divisions is documented in the dossier.</p>",
 "localsOnly": "<p>Welfare-board status and the documentation machinery of the 2019 Act and its 2026 amendment are resident-facing: the union-territory dependency described above bears on services and certificates for local transgender people rather than on how visitors are treated.</p>",
 "outOfScopeNotes": "<p>The amendment's operative status at time of writing is that both houses passed it and final assent is pending, so the controlling legal position for a traveler depends on that unresolved step; no Puducherry-specific statute, enforcement series or incident pattern is on file, and the transit-policing episode is a single documented complaint rather than a systematic series. No border or entry-paper practice specific to the division beyond the national medical-certification mandate is recorded in the dossier.</p>",
 "blindSummary": "<p>This state/province has a partial legislature: recognition and welfare policy for trans people is set principally by the national government, and no state/province-specific statute, enforcement series or incident pattern is on file.</p>\n<p>The framework that governs it shifted sharply in March 2026: the national legislature passed an amendment removing the self-identification right affirmed by the 2014 court ruling, restricting legal recognition to historically recognised communities and intersex people, and mandating medical certification for identity documents and for surgery; the medical-certification mandate is a direct documents consequence for a trans traveler whose papers now rest on that certification, and the change bears uniformly on every state/province, so it reaches visitors identically.</p>\n<p>Practical safety: a nationally recurring policing practice treats trans appearance as a suspicion category in transit spaces, evidenced by an August 2024 railway-platform groping complaint — a formal complaint was filed and intrusive questioning reported — reaching visitors through national transport policing rather than any local law.</p>",
 "blindTangential": "<p>National policy turbulence: the March 2026 amendment passed over warnings from critics and a court-appointed advisory panel that it excludes many trans, non-binary and gender-fluid people, with protests following the vote in several cities; the human-rights reporting calls the amendment a major reversal of the 2014 rights position, and the change bears uniformly on every state/province including this division. No litigation flux or comparison with neighbouring divisions is documented in the dossier.</p>",
 "blindLocalsOnly": "<p>Welfare-board status and the documentation machinery of the 2019 Act and its 2026 amendment are resident-facing: the status described above bears on services and certificates for local transgender people rather than on how visitors are treated.</p>",
 "blindOutOfScope": "<p>The amendment's operative status at time of writing is that both houses passed it and final assent is pending, so the controlling legal position for a traveler depends on that unresolved step; no state/province-specific statute, enforcement series or incident pattern is on file, and the transit-policing episode is a single documented complaint rather than a systematic series. No border or entry-paper practice specific to the division beyond the national medical-certification mandate is recorded in the dossier.</p>",
 "blindSourceSummaries": [
  "The 2026 trans-rights amendment bill amends the 2019 law: it removes the right to self-identification, limits legal recognition to historically accepted categories and intersex individuals, and mandates medical certification for identity recognition; the international rights organisation calls it a major reversal of the 2014 rights position and urges that it not be signed (reported 26 March 2026).",
  "Amendment bill approved by both houses (article 2026, awaiting final assent): removes the self-identification right affirmed by the 2014 'third gender' court ruling; narrows the 2019 definition of transgender person; the government says the narrower definition improves welfare delivery, critics warn it excludes trans men, trans women, non-binary and gender-fluid people; mandatory medical certification described as an attack on privacy and dignity."
 ],
 "notes": "current_localsOnly preserved in localsOnly; medical-certification mandate treated as documents/screening relevance in summary; protests/warnings and reversal characterisation to tangentialFactors; pending-assent status, single-episode and no-border-data caveats to outOfScopeNotes."
},
# ---------------------------------------------------------------- IND/Nāgāland
{
 "who": "IND/Nāgāland",
 "summary": "<p>Nagaland is assessed at the national score: the country dossier that covered this division identified no deviation from the national position material enough to score separately (within ±0.02). A visitor therefore stands under the national framework as altered by the 2026 amendment: parliament passed an amendment that removes the self-identification right affirmed by the 2014 Supreme Court ruling, restricts legal recognition to historically recognised communities and intersex people, and mandates medical certification for identity documents and for surgery, so identity-document practice for a trans traveler rests on that certification; the amendment had passed both houses and was awaiting assent at time of writing.</p>",
 "tangentialFactors": "<p>National policy turbulence: the amendment passed over warnings from critics and a court-appointed advisory panel that it excludes many trans, non-binary and gender-fluid people, with protests following the vote in several cities; the human-rights reporting calls the amendment a major reversal of the 2014 rights position, and the change bears uniformly on every state and union territory including this division. No litigation flux or comparison with neighbouring divisions is documented beyond the dossier finding.</p>",
 "localsOnly": "<p>Resident-facing content in the sourced claims: the government says the narrower definition improves welfare delivery — a resident-services rationale; no division-specific resident data is recorded in the dossier.</p>",
 "outOfScopeNotes": "<p>The assessment rests on the country dossier's no-material-deviation finding bounded by the ±0.02 threshold; no division-specific law, enforcement pattern or incident data is on file, and the amendment's operative status is that both houses passed it with final assent pending. No border or entry-paper practice specific to the division beyond the national medical-certification mandate is recorded in the dossier.</p>",
 "blindSummary": "<p>This state/province is assessed at the national score: the country dossier that covered this division identified no deviation from the national position material enough to score separately (within ±0.02). A visitor therefore stands under the national framework as altered by the 2026 amendment: the national legislature passed an amendment that removes the self-identification right affirmed by the 2014 court ruling, restricts legal recognition to historically recognised communities and intersex people, and mandates medical certification for identity documents and for surgery, so identity-document practice for a trans traveler rests on that certification; the amendment had passed both houses and was awaiting assent at time of writing.</p>",
 "blindTangential": "<p>National policy turbulence: the amendment passed over warnings from critics and a court-appointed advisory panel that it excludes many trans, non-binary and gender-fluid people, with protests following the vote in several cities; the human-rights reporting calls the amendment a major reversal of the 2014 rights position, and the change bears uniformly on every state/province including this division. No litigation flux or comparison with neighbouring divisions is documented beyond the dossier finding.</p>",
 "blindLocalsOnly": "<p>Resident-facing content in the sourced claims: the government says the narrower definition improves welfare delivery — a resident-services rationale; no division-specific resident data is recorded in the dossier.</p>",
 "blindOutOfScope": "<p>The assessment rests on the country dossier's no-material-deviation finding bounded by the ±0.02 threshold; no division-specific law, enforcement pattern or incident data is on file, and the amendment's operative status is that both houses passed it with final assent pending. No border or entry-paper practice specific to the division beyond the national medical-certification mandate is recorded in the dossier.</p>",
 "blindSourceSummaries": [
  "The 2026 trans-rights amendment bill amends the 2019 law: it removes the right to self-identification, limits legal recognition to historically accepted categories and intersex individuals, and mandates medical certification for identity recognition; the international rights organisation calls it a major reversal of the 2014 rights position and urges that it not be signed (reported 26 March 2026).",
  "Amendment bill approved by both houses (article 2026, awaiting final assent): removes the self-identification right affirmed by the 2014 'third gender' court ruling; narrows the 2019 definition of transgender person; the government says the narrower definition improves welfare delivery, critics warn it excludes trans men, trans women, non-binary and gender-fluid people; mandatory medical certification described as an attack on privacy and dignity."
 ],
 "notes": "Thin division record: dossier no-deviation finding kept in summary and tangentialFactors; sourced national-framework claims folded into the visitor summary per rule 6; welfare-delivery rationale to localsOnly; pending-assent and no-division-data caveats to outOfScopeNotes."
}
]

def main():
    existing = []
    if OUT.exists():
        try:
            existing = json.load(open(OUT)).get("rewrites", [])
        except Exception:
            existing = []
    keep = [r for r in existing if r.get("who") not in BATCH_WHOS]
    made = 0
    for rec in RECORDS:
        keep = [r for r in keep if r.get("who") != rec["who"]] + [rec]
        OUT.parent.mkdir(parents=True, exist_ok=True)
        json.dump({"rewrites": keep}, open(OUT, "w"), ensure_ascii=False, indent=1)
        made += 1
        print(f"wrote {made}/{len(RECORDS)} -> {rec['who']} (total {len(keep)})")

if __name__ == "__main__":
    main()