#!/usr/bin/env python3
"""Build data/split_out/s048.json (four-field split + blind mirrors) from s048 batch."""
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
batch = json.load(open(ROOT / "data/split_batches/s048.json", encoding="utf-8"))
recs = batch["records"]

C = {
 "PHL/Davao Region": {
  "summary": [
   "<p>Davao Region has no region-specific legal position on record; the framework a visitor stands under is the national one, and the country dossier records no separate local law, so the national framework applies here. Same-sex conduct is legal nationwide, but there is no legal gender recognition pathway, so identity documents cannot be brought into line with a trans visitor's presentation; there is no national anti-discrimination statute, and protection runs only through local non-discrimination ordinances. For a visitor the local layer matters most in the regional capital Davao City, where the city council's 2012 ordinance covers LGBT people, minorities and differently-abled persons.</p>",
   "<p>No region-specific enforcement, incident or practical-safety finding is recorded for the division, and the only regionally-dated datapoint is that 2012 Davao City ordinance. Same-sex marriage and civil unions have no legal recognition under the national framework, so no marriage-based or partner-travel status gives a visitor any local protection.</p>"],
  "tangential": [
   "<p>National calibration: the country dossier identified no deviation from the national position material enough to score separately (±0.02); it records no separate local law, so the national framework applies here and the division is assessed at the national score.</p>",
   "<p>Parent-nation policy turbulence: national equality legislation covering sexual orientation and gender identity has been filed since 1999 without enactment, and executive orders created a national diversity-and-inclusion programme in 2019, amended in 2023 to add a special committee, that audited reporting describes as unimplemented as of 2025. These are national-level developments rather than anything this region has enacted, and they colour the national environment rather than directly altering the visitor assessment above.</p>"],
  "localsOnly": [
   "<p>Resident-facing facts: anti-discrimination ordinances exist at city, municipal and provincial levels, so resident protection is patchwork and depends on where one lives. A 2018 national survey recorded 22% support for same-sex civil unions and a majority opposed to trans women's use of women's toilets; that attitude mix is resident data, not a visitor finding. The regional capital's 2012 local ordinance, set out above, is also the division's resident-facing law datapoint.</p>"],
  "outOfScope": [
   "<p>A June 2025 report on the killing of an 18-year-old trans woman concerns a different province (Cagayan), and a national news item on a case in another region (Batangas) could not be retrieved at fetch time; neither supports a region-specific claim. No border-screening or passport-marker practice for trans visitors is documented beyond the absence of a legal gender recognition pathway, and no enforcement data specific to this division is recorded. No marriage or partner-travel information beyond the national recognition position is recorded for this division.</p>"],
  "blindSummary": [
   "<p>This state/province has no region-specific legal position on record; the framework a visitor stands under is the national one, and the country dossier records no separate local law, so the national framework applies here. Same-sex conduct is legal nationwide, but there is no legal gender recognition pathway, so identity documents cannot be brought into line with a trans visitor's presentation; there is no national anti-discrimination statute, and protection runs only through local non-discrimination ordinances. For a visitor the local layer matters most in the regional capital, where the 2012 ordinance covers LGBT people, minorities and differently-abled persons.</p>",
   "<p>No region-specific enforcement, incident or practical-safety finding is recorded for the division, and the only regionally-dated datapoint is that 2012 capital ordinance. Same-sex marriage and civil unions have no legal recognition under the national framework, so no marriage-based or partner-travel status gives a visitor any local protection.</p>"],
  "blindTangential": [
   "<p>The country dossier records no separate local law, so the national framework applies here.</p>",
   "<p>Parent-nation policy turbulence: national equality legislation covering sexual orientation and gender identity has been filed since 1999 without enactment, and executive orders created a national diversity-and-inclusion programme in 2019, amended in 2023 to add a special committee, that audited reporting describes as unimplemented as of 2025. These are national-level developments rather than anything this state/province has enacted, and they colour the national environment rather than directly altering the visitor assessment above.</p>"],
  "blindLocalsOnly": [
   "<p>Resident-facing facts: anti-discrimination ordinances exist at city, municipal and provincial levels, so resident protection is patchwork and depends on where one lives. A 2018 national survey recorded 22% support for same-sex civil unions and a majority opposed to trans women's use of women's toilets; that attitude mix is resident data, not a visitor finding. The regional capital's 2012 local ordinance, set out above, is also the division's resident-facing law datapoint.</p>"],
  "blindOutOfScope": [
   "<p>A June 2025 report on the killing of an 18-year-old trans woman concerns a different province, and a national news item on a case in another state/province could not be retrieved at fetch time; neither supports a state/province-specific claim. No border-screening or passport-marker practice for trans visitors is documented beyond the absence of a legal gender recognition pathway, and no enforcement data specific to this state/province is recorded. No marriage or partner-travel information beyond the national recognition position is recorded for this state/province.</p>"],
  "blindSources": [
   "National rights-organisation overview (updated 12 March 2026): same-sex conduct is legal nationwide; there is no legal gender recognition pathway; an executive order signed in 2019 created a national diversity-and-inclusion programme, amended by a 2023 order to add a special LGBTQIA+ committee, with neither implemented as of 2025; anti-discrimination ordinances exist at neighbourhood, city, municipal and provincial levels, but national legislation filed since 1999 has not been enacted; a 2018 national survey found 22% support for same-sex civil unions and a majority opposed to trans women's access to women's toilets.",
   "National framework page (applies to this state/province, which records no separate state/province legislation; the national position plus any local ordinance of the state/province's administrative centre is what a visitor stands under): same-sex sexual activity is legal, but there is no national anti-discrimination statute, protection runs only in the basic-education context, with many local government non-discrimination ordinances filling the gap, and trans people are not allowed to change their legal gender. Same-sex marriage and civil unions have no national recognition, a family code defining marriage as between a man and a woman, and a national equality bill has been repeatedly filed without enactment. The page's local-government-ordinances section includes the administrative centre (2012) among localities with a non-discrimination ordinance, giving this state/province a dated, on-jurisdiction datapoint.",
   "A national news report (14 Dec 2012) that the administrative centre's local council passed an ordinance banning discrimination against gays (LGBT people), minorities and differently-abled persons, a direct dated report of the 2012 local non-discrimination ordinance that the national rights page cites as its 2012 entry; genuinely on-jurisdiction for this state/province, whose administrative centre is the regional capital.",
   "thin: no usable finding"],
  "notes": "Split from current_summary: national framework plus the 2012 Davao City ordinance as the on-the-ground visitor protection, no-regional-finding and marriage/partner-travel to summary; national equality bill and unimplemented executive-order programme to tangential; ordinance patchwork and 2018 resident survey to localsOnly; cross-region killing report, unretrievable other-region item and border/marriage caveats to outOfScope. current_tangential, current_localsOnly, current_outOfScope were empty."
 },
 "PHL/Caraga": {
  "summary": [
   "<p>Caraga records no documented region-specific law affecting trans people; the framework a visitor stands under is the national one. Same-sex conduct is legal, but there is no legal gender-recognition pathway, so identity documents cannot be brought into line with a trans visitor's presentation, and anti-discrimination protection runs only through local ordinances that exist at some city and provincial levels. The Safe Spaces Act criminalises homophobic and transphobic slurs, a national-level recourse a visitor can invoke. Butuan City, the regional capital and the most likely first port of call for a visitor, appears on the national list of localities with a non-discrimination ordinance (2016), the concrete on-jurisdiction protection here.</p>",
   "<p>No region-specific enforcement or incident finding is recorded for the division. Same-sex marriage and civil unions have no legal recognition under the national framework, so no marriage-based or partner-travel status gives a visitor any local advantage or protection.</p>"],
  "tangential": [
   "<p>National context and policy turbulence: the national equality bill has been filed repeatedly since 1999 without enactment, and executive orders created a national diversity-and-inclusion programme, amended in 2023 to add a special committee, that audited reporting describes as unimplemented as of 2025, national-level layers rather than anything this region has enacted. A June 2025 report on the killing of an eighteen-year-old trans student, which a national alliance presented as part of a pattern of violence against trans women, originates in a different region; for this division it counts only as part of the nationwide climate, not local evidence.</p>"],
  "localsOnly": [
   "<p>Resident-facing facts: school anti-bullying rules and gender-responsive education policy cover sexual-orientation and gender-identity grounds, protecting students rather than visitors. A 2018 national survey recorded about one-fifth support for same-sex civil unions and a majority opposed to trans women's use of women's toilets; that attitude mix is resident data, not a visitor finding.</p>"],
  "outOfScope": [
   "<p>No division-specific source beyond the capital's 2016 ordinance datapoint supports a local claim here, and the national-framework sources carry no Caraga-specific enforcement or incident detail. No border-screening or passport-marker practice for trans visitors is documented beyond the absence of a legal gender-recognition pathway, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSummary": [
   "<p>This state/province records no documented region-specific law affecting trans people; the framework a visitor stands under is the national one. Same-sex conduct is legal, but there is no legal gender-recognition pathway, so identity documents cannot be brought into line with a trans visitor's presentation, and anti-discrimination protection runs only through local ordinances that exist at some city and provincial levels. A national statute criminalises homophobic and transphobic slurs, a national-level recourse a visitor can invoke. The regional capital, the most likely first port of call for a visitor, appears on the national list of localities with a non-discrimination ordinance (2016), the concrete on-jurisdiction protection here.</p>",
   "<p>No region-specific enforcement or incident finding is recorded for the division. Same-sex marriage and civil unions have no legal recognition under the national framework, so no marriage-based or partner-travel status gives a visitor any local advantage or protection.</p>"],
  "blindTangential": [
   "<p>National context and policy turbulence: the national equality bill has been filed repeatedly since 1999 without enactment, and executive orders created a national diversity-and-inclusion programme, amended in 2023 to add a special committee, that audited reporting describes as unimplemented as of 2025, national-level layers rather than anything this state/province has enacted. A June 2025 report on the killing of an eighteen-year-old trans student, which a national alliance presented as part of a pattern of violence against trans women, originates in a different region; for this division it counts only as part of the nationwide climate, not local evidence.</p>"],
  "blindLocalsOnly": [
   "<p>Resident-facing facts: school anti-bullying rules and gender-responsive education policy cover sexual-orientation and gender-identity grounds, protecting students rather than visitors. A 2018 national survey recorded about one-fifth support for same-sex civil unions and a majority opposed to trans women's use of women's toilets; that attitude mix is resident data, not a visitor finding.</p>"],
  "blindOutOfScope": [
   "<p>No division-specific source beyond the capital's 2016 ordinance datapoint supports a local claim here, and the national-framework sources carry no state/province-specific enforcement or incident detail. No border-screening or passport-marker practice for trans visitors is documented beyond the absence of a legal gender-recognition pathway, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSources": [
   "National rights-organisation overview (updated 12 March 2026): same-sex conduct is legal nationwide; there is no legal gender recognition pathway; an executive order signed in 2019 created a national diversity-and-inclusion programme, amended by a 2023 order to add a special LGBTQIA+ committee, with neither implemented as of 2025; anti-discrimination ordinances exist at neighbourhood, city, municipal and provincial levels, but national legislation filed since 1999 has not been enacted; a 2018 national survey found 22% support for same-sex civil unions and a majority opposed to trans women's access to women's toilets.",
   "National framework page (applies to this state/province, which records no separate state/province regulation; the national position is what a visitor stands under): same-sex sexual activity is legal, but there is no national anti-discrimination law, protection exists only in the basic-education context, with non-discrimination coverage left to local ordinances, and trans people cannot change their legal gender. Same-sex marriage or civil unions are not nationally recognised, a family code defining marriage as between a man and a woman, and a national equality bill has been filed repeatedly without enactment. Directly on-jurisdiction: the page's local-ordinance list includes the capital (2016) among localities with a non-discrimination ordinance.",
   "thin: no usable finding"],
  "notes": "Split from current_summary: national framework, Safe Spaces Act recourse, Butuan City 2016 ordinance and marriage/partner-travel position to summary; equality bill, unimplemented programme and the other-region killing report as nationwide-climate context to tangential; school/education protections and 2018 resident survey to localsOnly; no-local-source and border/marriage caveats to outOfScope. current_tangential, current_localsOnly, current_outOfScope were empty."
 },
 "CHL/RegiÃ³n de Antofagasta": {
  "summary": [
   "<p>Antofagasta Region was assessed at the national score (deviation ±0.02) after the dedicated country dossier found no region-specific legal, incident or enforcement finding, so the framework a visitor stands under is the national one: same-sex marriage and adoption have been legal since March 2022, the national hate-crime law has covered sexual orientation and gender identity since 2012, and legal gender recognition by self-determination has existed since 2019, so a trans visitor's documents can be aligned to identity. The 2025 annual report of the national rights association places this region at 2.09% of nationally documented abuse cases, up from 1.32% in 2024, a +45.45% year-on-year rise and the second-largest increase of any region.</p>",
   "<p>The dossier's warning applies: a mid-share reading reflects documented hate diffusing into lower-visibility areas rather than safety, so the visitor takeaway is legality within a nationally documented rise in abuse cases.</p>"],
  "tangential": [
   "<p>Parent-nation dynamics: 2025 was a record year nationally, with 3,620 documented cases (+27.1%, the highest in 24 years) and only the two largest regions falling while the other fourteen rose; the national report reads the shift as hatred expanding into regions with less public debate. A further adjacent factor is a national rollback: the elected national legislature excluded the gender-identity support programme from the 2026 budget bill, a step condemned by civil society groups and the national children's ombudsman, political turbulence that does not change the legal position above.</p>"],
  "localsOnly": [
   "<p>Resident-facing facts: a third sex option has been available on birth certificates since 2006, a birth-register practice that concerns residents rather than visitors. The abuse-case figures above are nationally tallied resident discrimination data, and no resident survey or cultural-role fact beyond these is recorded for this region specifically.</p>"],
  "outOfScope": [
   "<p>The 2024 share (1.32%) cited in the comparison is not reproduced in the 2025 annual report edition, so the direction of local change rests on the 2025 edition's own figures. No border-screening or passport-marker practice beyond the recognition framework above is documented, and the sources do not address marriage or partner-travel documentation for visitors beyond the legality of same-sex marriage.</p>"],
  "blindSummary": [
   "<p>This state/province was assessed under the national framework after the dedicated country dossier found no region-specific legal, incident or enforcement finding, so the framework a visitor stands under is the national one: same-sex marriage and adoption have been legal since March 2022, the national hate-crime law has covered sexual orientation and gender identity since 2012, and legal gender recognition by self-determination has existed since 2019, so a trans visitor's documents can be aligned to identity. The 2025 annual report of the national rights association places this state/province at 2.09% of nationally documented abuse cases, up from 1.32% in 2024, a +45.45% year-on-year rise and the second-largest increase of any state/province.</p>",
   "<p>The dossier's warning applies: a mid-share reading reflects documented hate diffusing into lower-visibility areas rather than safety, so the visitor takeaway is legality within a nationally documented rise in abuse cases.</p>"],
  "blindTangential": [
   "<p>Parent-nation dynamics: 2025 was a record year nationally, with 3,620 documented cases (+27.1%, the highest in 24 years) and only the two largest regions falling while the other fourteen rose; the national report reads the shift as hatred expanding into regions with less public debate. A further adjacent factor is a national rollback: the elected national legislature excluded the gender-identity support programme from the 2026 budget bill, a step condemned by civil society groups and the national children's ombudsman, political turbulence that does not change the legal position above.</p>"],
  "blindLocalsOnly": [
   "<p>Resident-facing facts: a third sex option has been available on birth certificates since 2006, a birth-register practice that concerns residents rather than visitors. The abuse-case figures above are nationally tallied resident discrimination data, and no resident survey or cultural-role fact beyond these is recorded for this state/province specifically.</p>"],
  "blindOutOfScope": [
   "<p>The 2024 share (1.32%) cited in the comparison is not reproduced in the 2025 annual report edition, so the direction of local change rests on the 2025 edition's own figures. No border-screening or passport-marker practice beyond the recognition framework above is documented, and the sources do not address marriage or partner-travel documentation for visitors beyond the legality of same-sex marriage.</p>"],
  "blindSources": [
   "A national rights organisation's country dossier (published March 2026) contains no state/province-specific legal, incident or enforcement finding, the basis for this record's national-framework assessment: same-sex marriage and adoption have been legal since March 2022; the hate-crime law has covered sexual orientation and gender identity since 2012; legal gender recognition by self-determination has existed since 2019; a third sex option on birth certificates has existed since 2006; and the 2025-26 rollback in which the national legislature excluded the gender-identity support programme from the 2026 budget bill, an action condemned by civil society groups and the national children's ombudsman. The dossier itself carries no division-specific information.",
   "A national rights association's annual report (published March 2026) supplies this record's division-specific figures: this state/province is placed at 2.09% of nationally documented abuse cases, with a +45.45% year-on-year rise, the second-largest increase after one other state/province (+150%). Nationally it records 3,620 cases and complaints of discrimination in 2025 (+27.1%, the highest in 24 years), with only the two largest regions falling while the other fourteen rose, and it reads the shift as hatred expanding into regions with less public debate, the reading this record's mid-share position rests on. The 2024 share cited in this record's comparison is not reproduced in this 2025 edition."],
  "notes": "Split from current_summary: national legal framework plus the division's case-share and rise and the dossier warning to summary; national record-year pattern, neighbour comparisons and the budget rollback to tangential; birth-certificate third-sex practice and abuse-case resident data to localsOnly; unreproduced 2024 share and border/marriage caveats to outOfScope. current_tangential, current_localsOnly, current_outOfScope were empty."
 },
 "CHL/RegiÃ³n de Atacama": {
  "summary": [
   "<p>Atacama Region was assessed at the national score (deviation ±0.02) after the dedicated country dossier found no region-specific legal, incident or enforcement finding, so the framework a visitor stands under is the national one: same-sex marriage and adoption have been legal since March 2022, the hate-crime law has covered sexual orientation and gender identity since 2012, and legal gender recognition by self-determination has existed since 2019, letting a trans visitor's documents align to identity. The 2025 annual report of the national rights association places this region at 1.83% of nationally documented abuse cases (1.56% in 2024) with a +7.69% year-on-year rise, inside a national pattern in which most regions rose during 2025.</p>",
   "<p>No region-specific legal risk or enforcement finding qualifies the national picture; the visitor-facing read is legality under a national framework whose documented hate cases rose nationwide in 2025.</p>"],
  "tangential": [
   "<p>Adjacent circumstances: nationally 2025 was a record year with 3,620 documented cases (+27.1%, the highest in 24 years), with only the two largest regions falling while the other fourteen rose. Locally, the regional municipality convened the region's first Pride march during 2025 and hosted one of the marches that expanded the movement's territorial visibility; that institutional and social-climate positive colours a visit without being a legal protection. A further adjacent factor is a national rollback: the elected national legislature excluded the gender-identity support programme from the 2026 budget bill, condemned by civil society groups and the national children's ombudsman.</p>"],
  "localsOnly": [
   "<p>Resident-facing facts: a third sex option has been available on birth certificates since 2006, a birth-register practice that concerns residents rather than visitors. The abuse-case shares cited in the assessment are nationally tallied resident discrimination data, and no resident survey or cultural-role fact beyond these is recorded for this region.</p>"],
  "outOfScope": [
   "<p>The 2024 share (1.56%) cited in the comparison is not reproduced in the 2025 annual report edition, so the comparators rest on the current edition's figures. No border-screening or passport-marker practice beyond the recognition framework is documented, and the sources do not address marriage or partner-travel documentation for visitors beyond the legality of same-sex marriage.</p>"],
  "blindSummary": [
   "<p>This state/province was assessed under the national framework after the dedicated country dossier found no region-specific legal, incident or enforcement finding, so the framework a visitor stands under is the national one: same-sex marriage and adoption have been legal since March 2022, the hate-crime law has covered sexual orientation and gender identity since 2012, and legal gender recognition by self-determination has existed since 2019, letting a trans visitor's documents align to identity. The 2025 annual report of the national rights association places this state/province at 1.83% of nationally documented abuse cases (1.56% in 2024) with a +7.69% year-on-year rise, inside a national pattern in which most regions rose during 2025.</p>",
   "<p>No region-specific legal risk or enforcement finding qualifies the national picture; the visitor-facing read is legality under a national framework whose documented hate cases rose nationwide in 2025.</p>"],
  "blindTangential": [
   "<p>Adjacent circumstances: nationally 2025 was a record year with 3,620 documented cases (+27.1%, the highest in 24 years), with only the two largest regions falling while the other fourteen rose. Locally, the regional municipality convened the region's first Pride march during 2025 and hosted one of the marches that expanded the movement's visibility; that institutional and social-climate positive colours a visit without being a legal protection. A further adjacent factor is a national rollback: the elected national legislature excluded the gender-identity support programme from the 2026 budget bill, condemned by civil society groups and the national children's ombudsman.</p>"],
  "blindLocalsOnly": [
   "<p>Resident-facing facts: a third sex option has been available on birth certificates since 2006, a birth-register practice that concerns residents rather than visitors. The abuse-case shares cited in the assessment are nationally tallied resident discrimination data, and no resident survey or cultural-role fact beyond these is recorded for this state/province.</p>"],
  "blindOutOfScope": [
   "<p>The 2024 share (1.56%) cited in the comparison is not reproduced in the 2025 annual report edition, so the comparators rest on the current edition's figures. No border-screening or passport-marker practice beyond the recognition framework is documented, and the sources do not address marriage or partner-travel documentation for visitors beyond the legality of same-sex marriage.</p>"],
  "blindSources": [
   "A national rights organisation's country dossier (published March 2026) contains no state/province-specific legal, incident or enforcement finding, the basis for this record's national-framework assessment: same-sex marriage and adoption have been legal since March 2022; the hate-crime law has covered sexual orientation and gender identity since 2012; legal gender recognition by self-determination has existed since 2019; a third sex option on birth certificates has existed since 2006; and the 2025-26 rollback in which the national legislature excluded the gender-identity support programme from the 2026 budget bill, an action condemned by civil society groups and the national children's ombudsman. The dossier itself carries no division-specific information.",
   "A national rights association's annual report (published March 2026) supplies this record's division-specific figures: this state/province is placed at 1.83% of nationally documented abuse cases (1.56% in 2024) with a +7.69% year-on-year rise, and two positives are recorded locally: the regional municipality convened the region's first Pride march, and this state/province and one other became the first to hold Pride marches during 2025, expanding the movement's visibility. Nationally it records 3,620 cases and complaints of discrimination in 2025 (+27.1%, the highest in 24 years), with only the two largest regions falling while the other fourteen rose; it reads the shift as hatred expanding into regions with less public debate. The 2024 share cited in this record's comparison is not reproduced in this 2025 edition."],
  "notes": "Split from current_summary: national legal framework and the local case-share with rise to summary; national record-year pattern, neighbour comparisons, the municipal Pride-march positive and the budget rollback to tangential; birth-certificate third-sex practice and abuse-case resident data to localsOnly; unreproduced 2024 share and border/marriage caveats to outOfScope. current_tangential, current_localsOnly, current_outOfScope were empty."
 },
 "KOR/Gangwon": {
  "summary": [
   "<p>No province-specific law, ordinance or enforcement pattern targeting trans people is documented for Gangwon; the framework a visitor meets here is the national one: being trans is not criminalised, and the courts are steadily tightening what legal gender recognition may demand. A May 2024 ruling ended any surgical requirement for changing registered sex, and in July 2024 a court held that police telling a trans person to avoid public restrooms for a while infringed their rights, awarding damages after both instances found for the claimant, with an appellate court calling comfortable restroom use a fundamental and universal human right.</p>",
   "<p>For a visitor the operational reality is documented social friction around public restrooms, reported nationally rather than locally: Gangwon's audited record offers legality, functioning courts, no documented local hostility machinery, and no local facility-restriction law; restroom friction is a national-pattern finding, not a Gangwon one.</p>"],
  "tangential": [
   "<p>Litigation flux: the recognition-and-facility framework is being advanced through court rulings, the May 2024 and July 2024 decisions above plus a 2021 damages case the assessments cite, rather than through legislation; no province-specific development is recorded for this division in either direction.</p>"],
  "localsOnly": [
   "<p>Resident-facing data: a 2021 national survey of 591 trans respondents recorded everyday restroom avoidance in large majorities, 41% had used a facility mismatching their identity, 39% restricted food and drink, and 36% forwent restroom use, resident experience rather than visitor-specific risk. A 2021 damages award against a private academy that barred a trans student from its restroom shows the courts intervene when facilities are denied to residents, with both instances finding for the claimant.</p>"],
  "outOfScope": [
   "<p>The sources carry no Gangwon-specific incident or enforcement content; all findings above are national-level. No border-screening or passport-marker practice for trans visitors is documented beyond the court-approval regime for registered-sex change, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSummary": [
   "<p>No province-specific law, ordinance or enforcement pattern targeting trans people is documented for this state/province; the framework a visitor meets here is the national one: being trans is not criminalised, and the courts are steadily tightening what legal gender recognition may demand. A May 2024 ruling ended any surgical requirement for changing registered sex, and in July 2024 a court held that police telling a trans person to avoid public restrooms for a while infringed their rights, awarding damages after both instances found for the claimant, with an appellate court calling comfortable restroom use a fundamental and universal human right.</p>",
   "<p>For a visitor the operational reality is documented social friction around public restrooms, reported nationally rather than locally: the audited record for this state/province offers legality, functioning courts, no documented local hostility machinery, and no local facility-restriction law; restroom friction is a national-pattern finding, not a local one.</p>"],
  "blindTangential": [
   "<p>Litigation flux: the recognition-and-facility framework is being advanced through court rulings, the May 2024 and July 2024 decisions above plus a 2021 damages case the assessments cite, rather than through legislation; no state/province-specific development is recorded for this division in either direction.</p>"],
  "blindLocalsOnly": [
   "<p>Resident-facing data: a 2021 national survey of 591 trans respondents recorded everyday restroom avoidance in large majorities, 41% had used a facility mismatching their identity, 39% restricted food and drink, and 36% forwent restroom use, resident experience rather than visitor-specific risk. A 2021 damages award against a private academy that barred a trans student from its restroom shows the courts intervene when facilities are denied to residents, with both instances finding for the claimant.</p>"],
  "blindOutOfScope": [
   "<p>The sources carry no state/province-specific incident or enforcement content; all findings above are national-level. No border-screening or passport-marker practice for trans visitors is documented beyond the court-approval regime for registered-sex change, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSources": [
   "A national newspaper (22 July 2024): the appellate court dismissed the government's appeal and finalised a damages award, ruling that police advice to a person transitioning from male to female, who had obtained court approval for a family-register gender change in 2020, to avoid women's public restrooms infringed personal rights; the appellate court held that comfortable restroom use is a fundamental and universal human right. The article also reports a 2021 national human-rights commission survey of 591 trans respondents (41% had used a restroom of a different gender, 39% avoided food and drink, 36% forwent restroom use) and a 2021 damages award by a regional court against a beauty academy that prohibited a trans student from using its restroom. This is the national framework this state/province is assessed under; no state/province-specific incident appears.",
   "A national wire service (8 May 2024): a regional court approved changing the registered sex from male to female for five trans applicants without sex-reassignment surgery, holding that it is against the law to determine gender change based on surgery and that court guidelines requiring surgery are now only reference, not criteria; the court said every human being has the right to form their character and live a life according to their gender identity. The ruling removed the surgical prerequisite for registered-sex change and is the framework this state/province is assessed under; the wire contains no state/province-specific content."],
  "notes": "Split from current_summary: national legality, the May 2024 and July 2024 rulings and the practical-safety note to summary; litigation-flux framing to tangential; 2021 survey and academy-award resident data to localsOnly; no-local-incident and border/marriage caveats to outOfScope. current_tangential, current_localsOnly, current_outOfScope were empty."
 },
 "KOR/Incheon": {
  "summary": [
   "<p>Incheon is documented as a place with no specific local laws, ordinances or incident patterns concerning trans people; visitors stand under the national framework, favourable on paper and improving through litigation: trans status is not a crime; a May 2024 ruling confirmed surgery cannot be required to change registered legal sex; and in July 2024 a court held that police directing a transitioning person to avoid public restrooms infringed personal rights, with an appellate court calling comfortable restroom use a fundamental and universal human right.</p>",
   "<p>That mix, lawful status, an active and increasingly sympathetic judiciary, and socially contested facilities, is the documented experience of the division.</p>"],
  "tangential": [
   "<p>Litigation flux: the recognition-and-facility framework is being advanced through court decisions, the May 2024 and July 2024 rulings and a 2021 damages case, rather than through legislation.</p>"],
  "localsOnly": [
   "<p>Resident-facing data: a 2021 national survey of trans respondents documents fear-driven restroom avoidance in striking majorities, 41% had used a facility mismatching their identity and 36% forwent restroom use, resident experience rather than visitor-specific risk. A 2021 damages award against a private academy that excluded a trans student shows the courts intervene when facilities are denied to residents.</p>"],
  "outOfScope": [
   "<p>No municipality-level initiative is recorded for this division either way, and the sources carry no Incheon-specific incident or enforcement content. No border-screening or passport-marker practice for trans visitors is documented beyond the court-approval regime for registered-sex change, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSummary": [
   "<p>This state/province is documented as a place with no specific local laws, ordinances or incident patterns concerning trans people; visitors stand under the national framework, favourable on paper and improving through litigation: trans status is not a crime; a May 2024 ruling confirmed surgery cannot be required to change registered legal sex; and in July 2024 a court held that police directing a transitioning person to avoid public restrooms infringed personal rights, with an appellate court calling comfortable restroom use a fundamental and universal human right.</p>",
   "<p>That mix, lawful status, an active and increasingly sympathetic judiciary, and socially contested facilities, is the documented experience of the division.</p>"],
  "blindTangential": [
   "<p>Litigation flux: the recognition-and-facility framework is being advanced through court decisions, the May 2024 and July 2024 rulings and a 2021 damages case, rather than through legislation.</p>"],
  "blindLocalsOnly": [
   "<p>Resident-facing data: a 2021 national survey of trans respondents documents fear-driven restroom avoidance in striking majorities, 41% had used a facility mismatching their identity and 36% forwent restroom use, resident experience rather than visitor-specific risk. A 2021 damages award against a private academy that excluded a trans student shows the courts intervene when facilities are denied to residents.</p>"],
  "blindOutOfScope": [
   "<p>No municipality-level initiative is recorded for this division either way, and the sources carry no state/province-specific incident or enforcement content. No border-screening or passport-marker practice for trans visitors is documented beyond the court-approval regime for registered-sex change, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSources": [
   "A national newspaper (22 July 2024): the appellate court dismissed the government's appeal and finalised a damages award, ruling that police advice to a person transitioning from male to female, who had obtained court approval for a family-register gender change in 2020, to avoid women's public restrooms infringed personal rights; the appellate court held that comfortable restroom use is a fundamental and universal human right. The article also reports a 2021 national human-rights commission survey of 591 trans respondents (41% had used a restroom of a different gender, 39% avoided food and drink, 36% forwent restroom use) and a 2021 damages award by a regional court against a beauty academy that prohibited a trans student from using its restroom. This is the national framework this state/province is assessed under; no state/province-specific incident appears.",
   "A national wire service (8 May 2024): a regional court approved changing the registered sex from male to female for five trans applicants without sex-reassignment surgery, holding that it is against the law to determine gender change based on surgery and that court guidelines requiring surgery are now only reference, not criteria; the court said every human being has the right to form their character and live a life according to their gender identity. The ruling removed the surgical prerequisite for registered-sex change and is the framework this state/province is assessed under; the wire contains no state/province-specific content."],
  "notes": "Split from current_summary: national framework and the two rulings to summary; litigation-flux framing to tangential; 2021 survey and academy-award resident data to localsOnly; no-municipal-initiative, no-local-incident and border/marriage caveats to outOfScope. current_tangential, current_localsOnly, current_outOfScope were empty."
 },
 "KOR/North Jeolla": {
  "summary": [
   "<p>North Jeolla is covered by the dedicated country dossier, which records no separate local law, so the national framework applies here; the framework a visitor stands under is the national one: being trans is not criminalised; a May 2024 ruling ended any surgical requirement for changing registered sex, so changing registered sex is available through court approval without surgery; and a July 2024 appellate ruling held that police advising a transitioning person to avoid public restrooms for a while infringed personal rights, calling comfortable restroom use a fundamental and universal human right.</p>"],
  "tangential": [
   "<p>National calibration: the country dossier identified no deviation from the national position material enough to score separately (±0.02); it records no separate local law, so the national framework applies here and the division is assessed at the national score.</p>",
   "<p>Parent-nation legal climate: the recognition framework is changing through the courts rather than through legislation, and the dossier identifies no province-specific development for this division in either direction.</p>"],
  "localsOnly": [
   "<p>Resident-facing data: a 2021 national survey of 591 trans respondents recorded restroom avoidance in large majorities (41% had used a facility mismatching their identity, 39% restricted food and drink, 36% forwent restroom use), and a 2021 damages award against an academy that barred a trans student from its restroom shows recourse exists, resident and student experience, not a visitor finding.</p>"],
  "outOfScope": [
   "<p>The sources carry no North Jeolla-specific content; every finding above is national-level. No border-screening or passport-marker practice for trans visitors is documented beyond the court-approval regime for registered-sex change, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSummary": [
   "<p>This state/province is covered by the dedicated country dossier, which records no separate local law, so the national framework applies here; the framework a visitor stands under is the national one: being trans is not criminalised; a May 2024 ruling ended any surgical requirement for changing registered sex, so changing registered sex is available through court approval without surgery; and a July 2024 appellate ruling held that police advising a transitioning person to avoid public restrooms for a while infringed personal rights, calling comfortable restroom use a fundamental and universal human right.</p>"],
  "blindTangential": [
   "<p>The country dossier records no separate local law, so the national framework applies here.</p>",
   "<p>Parent-nation legal climate: the recognition framework is changing through the courts rather than through legislation, and the dossier identifies no state/province-specific development for this division in either direction.</p>"],
  "blindLocalsOnly": [
   "<p>Resident-facing data: a 2021 national survey of 591 trans respondents recorded restroom avoidance in large majorities (41% had used a facility mismatching their identity, 39% restricted food and drink, 36% forwent restroom use), and a 2021 damages award against an academy that barred a trans student from its restroom shows recourse exists, resident and student experience, not a visitor finding.</p>"],
  "blindOutOfScope": [
   "<p>The sources carry no state/province-specific content; every finding above is national-level. No border-screening or passport-marker practice for trans visitors is documented beyond the court-approval regime for registered-sex change, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSources": [
   "A national newspaper (22 July 2024): the appellate court dismissed the government's appeal and finalised a damages award, ruling that police advice to a person transitioning from male to female, who had obtained court approval for a family-register gender change in 2020, to avoid women's public restrooms infringed personal rights; the appellate court held that comfortable restroom use is a fundamental and universal human right. The article also reports a 2021 national human-rights commission survey of 591 trans respondents (41% had used a restroom of a different gender, 39% avoided food and drink, 36% forwent restroom use) and a 2021 damages award by a regional court against a beauty academy that prohibited a trans student from using its restroom. This is the national framework this state/province is assessed under; no state/province-specific incident appears.",
   "A national wire service (8 May 2024): a regional court approved changing the registered sex from male to female for five trans applicants without sex-reassignment surgery, holding that it is against the law to determine gender change based on surgery and that court guidelines requiring surgery are now only reference, not criteria; the court said every human being has the right to form their character and live a life according to their gender identity. The ruling removed the surgical prerequisite for registered-sex change and is the framework this state/province is assessed under; the wire contains no state/province-specific content."],
  "notes": "Split from current_summary: national-score assessment plus the two rulings and documents regime to summary; litigation-driven change to tangential; 2021 survey and academy-award data to localsOnly; no-local-content and border/marriage caveats to outOfScope. current_tangential, current_localsOnly, current_outOfScope were empty."
 },
 "KOR/South Jeolla": {
  "summary": [
   "<p>South Jeolla is covered by the dedicated country dossier, which records no separate local law, so the national framework applies here; the framework a visitor stands under is the national one: being trans is not criminalised; a May 2024 ruling ended any surgical requirement for changing registered sex, so changing registered sex is available through court approval without surgery; and a July 2024 appellate ruling held that police advising a transitioning person to avoid public restrooms for a while infringed personal rights, calling comfortable restroom use a fundamental and universal human right.</p>"],
  "tangential": [
   "<p>National calibration: the country dossier identified no deviation from the national position material enough to score separately (±0.02); it records no separate local law, so the national framework applies here and the division is assessed at the national score.</p>",
   "<p>Parent-nation legal climate: the recognition framework is changing through the courts rather than through legislation, and the dossier identifies no province-specific development for this division in either direction.</p>"],
  "localsOnly": [
   "<p>Resident-facing data: a 2021 national survey of 591 trans respondents recorded restroom avoidance in large majorities (41% had used a facility mismatching their identity, 39% restricted food and drink, 36% forwent restroom use), and a 2021 damages award against an academy that barred a trans student from its restroom shows recourse exists, resident and student experience, not a visitor finding.</p>"],
  "outOfScope": [
   "<p>The sources carry no South Jeolla-specific content; every finding above is national-level. No border-screening or passport-marker practice for trans visitors is documented beyond the court-approval regime for registered-sex change, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSummary": [
   "<p>This state/province is covered by the dedicated country dossier, which records no separate local law, so the national framework applies here; the framework a visitor stands under is the national one: being trans is not criminalised; a May 2024 ruling ended any surgical requirement for changing registered sex, so changing registered sex is available through court approval without surgery; and a July 2024 appellate ruling held that police advising a transitioning person to avoid public restrooms for a while infringed personal rights, calling comfortable restroom use a fundamental and universal human right.</p>"],
  "blindTangential": [
   "<p>The country dossier records no separate local law, so the national framework applies here.</p>",
   "<p>Parent-nation legal climate: the recognition framework is changing through the courts rather than through legislation, and the dossier identifies no state/province-specific development for this division in either direction.</p>"],
  "blindLocalsOnly": [
   "<p>Resident-facing data: a 2021 national survey of 591 trans respondents recorded restroom avoidance in large majorities (41% had used a facility mismatching their identity, 39% restricted food and drink, 36% forwent restroom use), and a 2021 damages award against an academy that barred a trans student from its restroom shows recourse exists, resident and student experience, not a visitor finding.</p>"],
  "blindOutOfScope": [
   "<p>The sources carry no state/province-specific content; every finding above is national-level. No border-screening or passport-marker practice for trans visitors is documented beyond the court-approval regime for registered-sex change, and the sources do not address marriage or partner-travel documentation for visitors.</p>"],
  "blindSources": [
   "A national newspaper (22 July 2024): the appellate court dismissed the government's appeal and finalised a damages award, ruling that police advice to a person transitioning from male to female, who had obtained court approval for a family-register gender change in 2020, to avoid women's public restrooms infringed personal rights; the appellate court held that comfortable restroom use is a fundamental and universal human right. The article also reports a 2021 national human-rights commission survey of 591 trans respondents (41% had used a restroom of a different gender, 39% avoided food and drink, 36% forwent restroom use) and a 2021 damages award by a regional court against a beauty academy that prohibited a trans student from using its restroom. This is the national framework this state/province is assessed under; no state/province-specific incident appears.",
   "A national wire service (8 May 2024): a regional court approved changing the registered sex from male to female for five trans applicants without sex-reassignment surgery, holding that it is against the law to determine gender change based on surgery and that court guidelines requiring surgery are now only reference, not criteria; the court said every human being has the right to form their character and live a life according to their gender identity. The ruling removed the surgical prerequisite for registered-sex change and is the framework this state/province is assessed under; the wire contains no state/province-specific content."],
  "notes": "Split as for KOR/North Jeolla: national-score assessment plus rulings and documents regime to summary; litigation-driven change to tangential; 2021 survey and academy-award data to localsOnly; no-local-content and border/marriage caveats to outOfScope. current_tangential, current_localsOnly, current_outOfScope were empty."
 }
}

def build(rec):
    who = rec["who"]
    spec = C[who]
    return {
        "who": who,
        "summary": "".join(spec["summary"]),
        "tangentialFactors": "".join(spec["tangential"]),
        "localsOnly": "".join(spec["localsOnly"]),
        "outOfScopeNotes": "".join(spec["outOfScope"]),
        "blindSummary": "".join(spec["blindSummary"]),
        "blindTangential": "".join(spec["blindTangential"]),
        "blindLocalsOnly": "".join(spec["blindLocalsOnly"]),
        "blindOutOfScope": "".join(spec["blindOutOfScope"]),
        "blindSourceSummaries": spec["blindSources"],
        "notes": spec["notes"],
    }

out = {"rewrites": []}
out_path = ROOT / "data" / "split_out" / "s048.json"
# merge-first: keep any pre-existing rewrites (from other whos), add/replace ours per record
prev = {}
if out_path.exists():
    prev = {r["who"]: r for r in json.load(open(out_path, encoding="utf-8"))["rewrites"]}
for rec in recs:
    who = rec["who"]
    if who not in C:
        sys.exit(f"NOT IMPLEMENTED: {who}")
    prev[who] = build(rec)
    out["rewrites"] = list(prev.values())
    out_path.write_text(json.dumps(out, ensure_ascii=False, indent=1), encoding="utf-8")
print(f"wrote {len(out['rewrites'])} rewrites -> {out_path}")